### ISSUE TITLE
Desktop: scroll by mouse-wheel

### ISSUE THREAD

**Issue by espresso3389** [espresso3389/pdfrx#10]
Currently, PdfViewer does not support scroll by mouse-wheel on desktop platforms.
We'd better support scroll by mouse-wheel but we should investigate the way to implement it.

According to flutter/flutter#121961, they don't want to implement scroll by mouse-wheel on [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html) anyway.

So, the approach may be one of

- Forking InteractiveViewer to implement our own scroll by mouse-wheel feature
- Switching the container to [TwoDimensionalScrollable ](https://api.flutter.dev/flutter/widgets/TwoDimensionalScrollable-class.html)

**Comment by mlican** [comment]
You can refer to the following ideas, but I haven't written the specific code yet. First, set the `scaleEnabled` parameter of `InteractiveViewer` to `false`. Outside of `InteractiveViewer`, use a `Listener` to listen for `onPointerSignal`, for example:
```dart
Timer? _scrollTimer;  
bool isScrolled = false; 


return Listener(  
  onPointerSignal: (event) {
  isScrolled = true;  
  if (event is PointerScrollEvent) {  
    /// Set scroll position  
    jumpTo(  
        xOffset: currentOffset.dx + event.scrollDelta.dx,  
        yOffset: currentOffset.dy + event.scrollDelta.dy);  
  }  
  _scrollTimer?.cancel();  
  _scrollTimer = Timer(  
    const Duration(milliseconds: 100),  
    () {  
      isScrolled = false;  
    },  
  );  
  },  
  child: Container(  
    color: widget.params.backgroundColor,  
    child: Stack(  
      children: [  
        InteractiveViewer(
        ......
```

**Comment by espresso3389** [comment]
I'm just considering to fork the original InteractiveViewer to support scroll-by-mouse-wheel.
If we just simply wrap InteractiveViewer with Listener, it kills some of InteractiveViewer features such as touchpad support. I don't want to kill them but need better mouse-wheel support.

**Comment by espresso3389** [comment]
[0.3.2](https://pub.dev/packages/pdfrx/versions/0.3.2) now supports `PdfViewerParams.scrollByMouseWheel` to specify wheel-delta to scroll ratio. If it is `null`, it defaults the InteractiveViewer's wheel-to-scale behavior.
