### ISSUE TITLE
_pdfcontroller issue

### ISSUE THREAD

**Issue by dhruvhighspot** [espresso3389/pdfrx#100]
showing null outside the "viewerOverlayBuilder:" controller values are not passing globally
```
 testWidgets('Test PDF Viewer with completed download', (WidgetTester tester) async {
    final PdfViewerController _pdfViewerController = PdfViewerController();
    final MaterialApp materialApp = MaterialApp(
      home: Scaffold(
        body: PdfViewer.asset(
          "test.pdf",
          controller: _pdfViewerController,
        ),
      ),
    );

    await tester.pumpWidget(materialApp);
    expect(find.byType(PdfViewer), findsOneWidget);
    print("TEST: ${_pdfViewerController.pageNumber}");
  });
```

Output:

flutter test test/widgets/content_views/hs_pdf_view_new_test.dart
00:02 +2: Test PDF Viewer with completed download                                                                                                                               
TEST: null
00:02 +3: All tests passed!

**Comment by espresso3389** [comment]
pumpWidget is not enough to wait for loading document.
Please use [PdfViewerParams.onViewerReady](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/onViewerReady.html).
