### ISSUE TITLE
pdfcontroller returning null

### ISSUE THREAD

**Issue by dhruvhighspot** [espresso3389/pdfrx#101]
controller outside viewerOverlayBuilder returning null
` testWidgets('Test PDF Viewer with completed download', (WidgetTester tester) async {
    final PdfViewerController _pdfViewerController2 = PdfViewerController();
    final MaterialApp materialApp = MaterialApp(
      home: Scaffold(
        body: PdfViewer.asset(
          "test.pdf",
          controller: _pdfViewerController2,
        ),
      ),
    );

    await tester.pumpWidget(materialApp);
    expect(find.byType(PdfViewer), findsOneWidget);
    print("TEST: ${_pdfViewerController2.pageNumber}");
  });`
  
  flutter test test/widgets/content_views/hs_pdf_view_new_test.dart
00:02 +2: Test PDF Viewer with completed download                                                                                                                               
TEST: null
00:02 +3: All tests passed!

**Comment by dhruvhighspot** [comment]
similar to 100

**Comment by espresso3389** [comment]
What are you doing? It seems identical to #100...
