### ISSUE TITLE
minScale parameter does not work 

### ISSUE THREAD

**Issue by FeofanGreek** [espresso3389/pdfrx#105]
When the minScale parameter is set to any value, the decrease occurs to infinity. You can play by resizing with two fingers

**Comment by DonRubiczek** [comment]
There was already a conversation about this. From what I understood, the parameter is supposed to work from the next version.

https://github.com/espresso3389/pdfrx/issues/89#issuecomment-1988495302

**Comment by espresso3389** [comment]
1.0.50/0.4.50/0.0.50 introduces `PdfViewerParams.useAlternativeFitScaleAsMinScale`, You can set the value to false to enable `minScale`.
