### ISSUE TITLE
Drawing on pdf

### ISSUE THREAD

**Issue by Cersin** [espresso3389/pdfrx#106]
Hi,
its drawing on pdf file possible?
I need something like selecting text to make a bookmark but I need to select an area, maybe some rectangle to mark some area of the pdf.

Maybe there is a way to achieve that?

**Comment by espresso3389** [comment]
There are two ways to do that:

- [PdfViewerParams.pageOverlaysBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pageOverlaysBuilder.html) is to add several widgets on each page. You may need to place GestureDetector or such on each page.
- [PdfViewerParams.pagePaintCallbacks](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pagePaintCallbacks.html) is to draw on each page's canvas.

The second one is not needed if you can do your jobs using widgets only. But if you want to place many widgets on a page, it may degrade the page rendering speed and you may want to switch to the second one.

**Comment by espresso3389** [comment]
For the first one, there's no solid sample now but its parent is Stack and you can place Align or Positioned to place child widgets.

There's [a sample](https://github.com/espresso3389/pdfrx/blob/master/example/viewer/lib/main.dart#L343) for the second one that shows marker highlight. You should firstly check the pdfrx's example code.

**Comment by Cersin** [comment]
> There are two ways to do that:
> 
> * [PdfViewerParams.pageOverlaysBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pageOverlaysBuilder.html) is to add several widgets on each page. You may need to place GestureDetector or such on each page.
> * [PdfViewerParams.pagePaintCallbacks](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pagePaintCallbacks.html) is to draw on each page's canvas.
> 
> The second one is not needed if you can do your jobs using widgets only. But if you want to place many widgets on a page, it may degrade the page rendering speed and you may want to switch to the second one.

but how do i place a rectangle and get good coordinates from pdf to draw on it?
i will appreciate any help, you are good guy :)

**Comment by Cersin** [comment]
@espresso3389 oooh i got it, thanks!

**Comment by jaween** [comment]
@Cersin 

Here's what I have. The `pageOverlaysBuilder` has a `page` parameter with a `width` and `height` measured in physical `points` (1/72 of an inch). It also has a `pageRect` which represents the page's bounds relative to the `PdfViewer` in logical pixels. This is all we need to convert between points and pixels.

To convert a pixel to a point horizontally, you could use:
```dart
final pixelToPointX = page.width / pageRect.width;
final myPixel = 200.0; // From a gesture detector perhaps
final myPoint = myPixel * pixelToPointX;
```
Vertical is the same process. To convert a point to a pixel just divide by `pixelToPoint`.
