### ISSUE TITLE
scale the pdf when scaling the browser tab

### ISSUE THREAD

**Issue by MarcVanDaele90** [espresso3389/pdfrx#114]
I'm using your library on Web. 

When I create a pdf widget with 
```
PdfViewer.uri(
      Uri.parse(widget.pdfUrl),
)
```
the text is initially scaled such that it fits the width.

When I scale the browser window, the text is not scaled (and a horizontal thumb is shown if configured).
I would like the text to scale such that it fits the width again.
Is this possible?

**Comment by allalakhayri** [comment]
Hi @MarcVanDaele90  , can you share your widget please with pdfrx on web , am having some issues . Thanks !

**Comment by MarcVanDaele90** [comment]
Hi @allalakhayri I just started from the example from https://github.com/espresso3389/pdfrx/tree/master/example/viewer/lib ?  Which issues do you encounter exactly?
