### ISSUE TITLE
Long time to load large PDF files

### ISSUE THREAD

**Issue by davidengler** [espresso3389/pdfrx#115]
When I try to open a pdf file with like 2000 pages, it takes a long time (about 10 sec).
This is not a major issue, but nice to have. Thank you for creating this package.

**Comment by espresso3389** [comment]
I don't have so large PDF file but I found the following PDF file has 618 pages.

https://www.nasa.gov/wp-content/uploads/static/history/alsj/a17/A17_FlightPlan.pdf

Loading it takes a little longer but still acceptable. I need larger ones...
