### ISSUE TITLE
Can I customize the box when I finish selecting the text? Are there any callbacks for table/picture clicks?

### ISSUE THREAD

**Issue by MRYIN123** [espresso3389/pdfrx#120]
Is there a selectArea for selecting text on macos? Can you open the callback after selecting the text, so that you can customize the pop-up box when selecting the text. Are there any callbacks for table/picture clicks?

**Comment by espresso3389** [comment]
1.0.54 introduces `PdfViewerParams.perPageSelectionAreaInjector to customize text selection behavior:

```dart
perPageSelectionAreaInjector: (page, child) {
  return SelectionArea(
    contextMenuBuilder: (context, selectableRegionState) {
      return AdaptiveTextSelectionToolbar.selectableRegion(
         selectableRegionState: selectableRegionState,
      );
    },
    child: child,
  );
},
```

**Comment by MRYIN123** [comment]
Thanks!

**Comment by espresso3389** [comment]
You can inject any widget other than SelectionArea so that do some special trick.

But I understand that it is just the first step and could not customize everything (I don't know what should be customizable) so far.
