### ISSUE TITLE
Provide an optional function to clear the cache

### ISSUE THREAD

**Issue by zengchanghuan** [espresso3389/pdfrx#123]
In high-configuration apps, I can choose not to clear the cache, but in low-configuration apps, I can actively clear the cache.

**Comment by yhyh0** [comment]
> In high-configuration apps, I can choose not to clear the cache, but in low-configuration apps, I can actively clear the cache.

Not sure what you mean by high/low-configuration apps, but we probably shouldn't expose a function to "clear" the cache. I think it's a bit more about the language/framework environment we are in --- if it's C, then why not? But it's dart/Flutter, it might be better to stick with something like ```cacheExtent```.

But wait.. are we only talking about ```FPDF_RenderPageBitmap``` here? If so, we definitely do not want to expose Pdfium's caching logic..

**Comment by espresso3389** [comment]
1.0.55 introduces certain memory consumption optimization.
And there are several parameters that directly affects the memory consumption;

- [PdfViewerParams.maxImageBytesCachedOnMemory](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/maxImageBytesCachedOnMemory.html)
  - Determines maximum memory consumed by rendered page images
- [PdfViewerParams.getPageRenderingScale](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/getPageRenderingScale.html)
  - Determine page rendering scale that is cacled on memory if the scale is smaller, more pages can be cached on the memory 
- [PdfViewerParams.horizontalCacheExtent](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/horizontalCacheExtent.html)
  - Pages placed within the extent from the visible area is cached even if it is not shown in the visible area
- [PdfViewerParams.verticalCacheExtent](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/verticalCacheExtent.html)
  - Pages placed within the extent from the visible area is cached even if it is not shown in the visible area
 
I think that clearing the cache explicitly degrades the viewer performance and you had better think the parameters explained above to control the cache behavior indirectly.
