### ISSUE TITLE
Cannot run example app. Error: The type 'SelectionEventType' is not exhaustively matched by the switch cases since it doesn't match 'SelectionEventType.selectParagraph'.

### ISSUE THREAD

**Issue by Prithvi-raptee** [espresso3389/pdfrx#129]
Warning: In index.html:39: Manual service worker registration deprecated. Use flutter.js service worker bootstrapping instead.
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/pdfrx-1.0.55/lib/src/widgets/pdf_page_text_overlay.dart:435:19: Error: The type 'SelectionEventType' is not exhaustively matched by the switch cases since it doesn't match 'SelectionEventType.selectParagraph'.
 - 'SelectionEventType' is from 'package:flutter/src/rendering/selection.dart' ('/C:/src/flutter/packages/flutter/lib/src/rendering/selection.dart').
Try adding a default case or cases that match 'SelectionEventType.selectParagraph'.
    switch (event.type) {
                  ^
Failed to compile application.

I get a warning like this everyy time I run the example app, or use this package on my own app. I ran the code specifically for Linux, Windows and android and it did not work anywhere.

**Comment by espresso3389** [comment]
Please show your `flutter doctor -v`.

**Comment by Prithvi-raptee** [comment]
[√] Flutter (Channel master, 3.22.0-9.0.pre, on Microsoft Windows [Version 10.0.26058.1300], locale en-IN)
    • Flutter version 3.22.0-9.0.pre on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53cba24de3 (27 hours ago), 2024-04-11 21:07:19 -0700
    • Engine revision 6b37b17099
    • Dart version 3.5.0 (build 3.5.0-47.0.dev)
    • DevTools version 2.34.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\imail\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34009.444
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\imail\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26058.1300]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.105
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.39

[√] Network resources
    • All expected network resources are available.

**Comment by espresso3389** [comment]
You are using non-stable version and SelectionEventType.selectParagraph is not found on the stable version.

https://api.flutter.dev/flutter/rendering/SelectionEventType.html

**Comment by Prithvi-raptee** [comment]
C:\Windows\System32>flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (2 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

C:\Windows\System32>flutter --version
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (2 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

It says I am already on a stable channel.

**Comment by espresso3389** [comment]
Did you resolve the issue?

**Comment by Prithvi-raptee** [comment]
Yes. The fix that worked for me is that I downgraded the flutter version to the previous stable version and then upgraded it back to the higher stable version.
