### ISSUE TITLE
The method 'uri' isn't defined for the type 'PdfViewer'.

### ISSUE THREAD

**Issue by Yoda-Man** [espresso3389/pdfrx#13]
The method 'uri' isn't defined for the type 'PdfViewer'.

The method 'PdfViewerParams' isn't defined for the type '_ContentPDFPageState'.

Sample below
    final pdfpage = PdfViewer.uri(
      Uri.parse(current.url),
      controller: controller,
      displayParams: PdfViewerParams(
        maxScale: 8,
        enableTextSelection: !_isDesktop,
      ),
    );

**Comment by crystalleung926** [comment]
Hi, i am also facing this problem. I copied the code from your example on pub.dev

![image](https://github.com/espresso3389/pdfrx/assets/141908901/688998bc-1c9f-40fd-a118-50a6da2ea057)

and I found the PdfViewer is a StatefulWidget, not a normal class. Is it a typo? lol

**Comment by crystalleung926** [comment]
Hi, i am also facing this problem. I copied the code from your example on pub.dev
![image](https://github.com/espresso3389/pdfrx/assets/141908901/664d76ed-ac6c-4d4f-932c-db57ea22c6e4)



and I looked into the PdfViewer , it do not contain a contractor for uri or asset

**Comment by espresso3389** [comment]
I'm not sure what's happening on your side.
On my side, creating a new project with `pdfrx: ^0.3.3` just works. Which version of pdfrx are you using?
And, if possible, please show me your `flutter doctor -v`.

**Comment by crystalleung926** [comment]
Oh, I see the point, I used flutter pub add pdf_render, and the version is 0.1.1
now i upgrade to 0.3.3
it works fine now, thanks a lot~

**Comment by espresso3389** [comment]
Can I close the issue?

**Comment by Yoda-Man** [comment]
No not yet same issue

**Comment by Yoda-Man** [comment]
@ #``

**Comment by espresso3389** [comment]
@Yoda-Man 

Strange case with your issue is that `_ContentPDFPageState` is never defined in pdfrx. Did you mistakenly modify the source code?

So, please do the following to clear pub cache before building your code:

```
flutter pub cache clean
```

And, also please check pdfrx is updated to 0.3.3.

**Comment by Yoda-Man** [comment]
I see the problem

Because package_info_plus_web >=1.0.0-nullsafety.0 depends on http ^0.13.0 and package_info_plus_web <1.0.0-nullsafety.0 doesn't support null safety, every version of package_info_plus_web requires http ^0.13.0.
And because pdfrx >=0.2.0 depends on http ^1.1.2, package_info_plus_web is incompatible with pdfrx >=0.2.0.
So, because sc depends on both pdfrx ^0.3.3 and package_info_plus_web any, version solving failed.

**Comment by Yoda-Man** [comment]
Its working you can closer the bug
