### ISSUE TITLE
Support for annotations to handle internal URLs in a PDF

### ISSUE THREAD

**Issue by AdityaHighspot** [espresso3389/pdfrx#135]
Hey @espresso3389 
I'm wondering why we are able to use linkWidgetBuilder for handling external URLs, but don't have support for internal URLs on it?

e.g. when you click on a link that's pointing to another page in the same document, it should also be handled inside the same function. PFA sample PDF with links on top for browsing through the pages.
[dripbox.pdf](https://github.com/espresso3389/pdfrx/files/15057438/dripbox.pdf)

**Comment by espresso3389** [comment]
pdfrx does support in-PDF links but does not handle links in the document...

**Comment by AdityaHighspot** [comment]
Can you please tell me how to handle such links then?

**Comment by espresso3389** [comment]
It is just discovered that the PDF file has broken links. The rectangles's top and bottom coordinates are stored in wrong order (at least not expected order).
Anyway, we can easily detect/auto-fix such error so the newer code can handle them correctly.

**Comment by espresso3389** [comment]
1.0.56 includes the fix.
