### ISSUE TITLE
pagePaintCallbacks - add your own color

### ISSUE THREAD

**Issue by Sikman** [espresso3389/pdfrx#142]
Hi there,

I would like to add my own custom color for the matches inside of the PDF - the highlight color. Is that possible, or will be?

**Comment by espresso3389** [comment]
Good suggestion. It should be customizable. No, it must be.
Currently the colors are hard-coded I should work for the update.

**Comment by espresso3389** [comment]
On f002590, I've added `matchTextColor`/`activeMatchTextColor`:

https://github.com/espresso3389/pdfrx/blob/master/lib/src/widgets/pdf_viewer_params.dart#L146-L152

@Sikman Do you need more customizability?

**Comment by Sikman** [comment]
Awesome! I will try it. Thaks a lot

**Comment by Sikman** [comment]
@espresso3389 Works like a charm! 👍 Well done. Very useful feature
