### ISSUE TITLE
PDF not scrollable with finger(touch point) on smaller devices

### ISSUE THREAD

**Issue by Sikman** [espresso3389/pdfrx#144]
The user can't scroll through the PDF on smaller screens with its finger. Will that be possible?

**Comment by Sikman** [comment]
I would like to add it is not scrollable with mouse at all...Any touch point

**Comment by Sikman** [comment]
I have tested - works but only when we set enableTextSelection: false; Can this be somehow combined, so that both work?

**Comment by Sikman** [comment]
@espresso3389  The temporary solution can be - when is the smaller screen disable text selection:
enableTextSelection: !smallScreen;

Anyway people will not use on mobile the select functionality? But will be awesome when the touch point scroll function on all screens together with text selection works.

**Comment by espresso3389** [comment]
Now it works as expected.
