### ISSUE TITLE
Failed to load dynamic library 'libpdfium.so'

### ISSUE THREAD

**Issue by reddeath1** [espresso3389/pdfrx#145]
Invalid argument(s): Failed to load dynamic library 'libpdfium.so': dlopen failed: cannot locate symbol "strtof_l" referenced by "/data/app/com.mcl.egazeti-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libpdfium.so"...

#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      pdfium (package:pdfrx/src

Samsung J7 prime

**Comment by espresso3389** [comment]
According to [the google's document](https://android.googlesource.com/platform/bionic/+/master/docs/status.md), `strtof_l` is introduced on API level 26 (Oreo).

So Samsung J7 Prime is lower than it?

**Comment by reddeath1** [comment]
Thank you. Can you advise the solution for these devices.

**Comment by espresso3389** [comment]
1.0.60 updates pdfium to bblanchon/pdfium-binaries 125.0.6406.0 (chromium/6406)
that sets default_min_sdk_version=21 to support lower API level devices.

**Comment by reddeath1** [comment]
Thank you, I m upgrading to it now.

**Comment by espresso3389** [comment]
@reddeath1 So is the build working for the device? If so, please close the issue.

**Comment by reddeath1** [comment]
Thanks I've tested it on API 24, this is what I got but the pdf opened. 

`/data/app/com.m/lib/arm64/libpdfium.so: unused DT entry: type 0x70000001 arg 0x0`

**Comment by reddeath1** [comment]
The update works, thanks.
