### ISSUE TITLE
Document appearance

### ISSUE THREAD

**Issue by rvachev** [espresso3389/pdfrx#148]
Hi!

Thanks for developing such useful package!

May I ask you to add to your future plans feature to customize pdf page e.g. doc border (now it's black solid border), shadows and etc.?

Thanks in advance!

**Comment by espresso3389** [comment]
1.0.61 introduces PdfViewerParams.pageDropShadow/PdfViewerParams.pageBackgroundPaintCallbacks and the new version shows drop-shadow rather than solid border.
