### ISSUE TITLE
Can the ability to display a scrolling scrollbar be supported while viewing PDF?

### ISSUE THREAD

**Issue by mlican** [espresso3389/pdfrx#15]
Is it possible to enhance the PDF viewing experience by adding a scrollbar for easier navigation?

**Comment by espresso3389** [comment]
[0.4.0](https://pub.dev/packages/pdfrx/versions/0.4.0) is a new version which supports customization mechanism to add scroll thumbs:

```dart
PdfViewer.uri(
  Uri.parse('https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
  controller: controller,
  displayParams: PdfViewerParams(
    maxScale: 8,
    viewerOverlayBuilder: (context, size) => [
      // vertical scrollbar
      PdfViewerScrollThumb(
        controller: controller,
        orientation: ScrollbarOrientation.right,
        thumbSize: const Size(40, 25),
        thumbBuilder:
            (context, thumbSize, pageNumber, controller) =>
                Container(
          color: Colors.black,
          child: Center(
            child: Text(
              pageNumber.toString(),
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ),
      ),
      // of course, you can also add horizontal scrollbar if needed
      PdfViewerScrollThumb(
        controller: controller,
        orientation: ScrollbarOrientation.bottom,
        thumbSize: const Size(80, 30),
        thumbBuilder:
            (context, thumbSize, pageNumber, controller) =>
                Container(
          color: Colors.red,
        ),
      ),
    ],
  ),
),
```

**Comment by mlican** [comment]
> [0.4.0](https://pub.dev/packages/pdfrx/versions/0.4.0) is a new version which supports customization mechanism to add scroll thumbs:
> 
> ```dart
> PdfViewer.uri(
>   Uri.parse('https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
>   controller: controller,
>   displayParams: PdfViewerParams(
>     maxScale: 8,
>     viewerOverlayBuilder: (context, size) => [
>       // vertical scrollbar
>       PdfViewerScrollThumb(
>         controller: controller,
>         orientation: ScrollbarOrientation.right,
>         thumbSize: const Size(40, 25),
>         thumbBuilder:
>             (context, thumbSize, pageNumber, controller) =>
>                 Container(
>           color: Colors.black,
>           child: Center(
>             child: Text(
>               pageNumber.toString(),
>               style: const TextStyle(color: Colors.white),
>             ),
>           ),
>         ),
>       ),
>       // of course, you can also add horizontal scrollbar if needed
>       PdfViewerScrollThumb(
>         controller: controller,
>         orientation: ScrollbarOrientation.bottom,
>         thumbSize: const Size(80, 30),
>         thumbBuilder:
>             (context, thumbSize, pageNumber, controller) =>
>                 Container(
>           color: Colors.red,
>         ),
>       ),
>     ],
>   ),
> ),
> ```

Great! this is very helpful for me.

**Comment by espresso3389** [comment]
Oh, I didn't mention that the function is to generate Stack's children so that you can place Aligned, Positioned, and such to decorate the viewer. So if you need scrollbars instead of scroll thumbs,
you can do it yourself.
