### ISSUE TITLE
upgrade  intl ^0.18.1 to  intl ^0.19.0

### ISSUE THREAD

**Issue by ivanzhadnov** [espresso3389/pdfrx#151]
_

**Comment by federico-b-visia** [comment]
With Flutter 3.22 `flutter_localizations` depends on `intl 0.19.0`, could be useful to return back to `intl 0.19.0`

**Comment by espresso3389** [comment]
It's just complicated moment now. Some user goes Flutter 3.22 and others remain on older versions... So the only way to support intl 1.19.0 is pdfrx 1.1 series and it means two active branches :(

**Comment by espresso3389** [comment]
OK, I just removed dependency to intl and no intl upgrade issues!
