### ISSUE TITLE
Do not resize page on goToPage function

### ISSUE THREAD

**Issue by Sikman** [espresso3389/pdfrx#153]
I am using the goToPage function to go to the next or previous page. I have an issue, when I zoomIn the page, and I click on the goToPage, it will use a complete width which I have setted, will resize my document view. I would rather use the currentZoom width, so the UX satisfies the users needs. If the user wants to have always the e.g. 130%, and clicks on the arrow which triggers goToPage, to skip to next page, he would expect not to resize,fit,whatever the document view he uses.

**Comment by Sikman** [comment]
@espresso3389 Will you consider this? Thank you

**Comment by espresso3389** [comment]
1.0.68 introduces several breaing changes to PdfPageAnchor behavior.

Now, `PdfPageAnchor.topCenter` just keeps the top-center of the page visible inside the view but does not change the zoom ratio.

And, newly introduced `PdfPageAnchor.top` will always make the whole page top lines visible inside the view; if the page size is larger than the view size, it changes the zoom ratio to make the page width fit into the view.

Please evaluate the new behavior and please let me know if you have any questions or suggestions.
