### ISSUE TITLE
Does building the ipa install the required files every time, even if they exist?

### ISSUE THREAD

**Issue by LiWenHui96** [espresso3389/pdfrx#154]
There is a script command in `pdfrx.podspec` that needs to install the required files, but it will run every time. I wonder if I can determine if the file exists and no longer run this command.

**Comment by espresso3389** [comment]
You're right. We should cache the last downloaded result. The code there is not changed from the first version.
We should do some existance check there.

**Comment by espresso3389** [comment]
I've updated podspec file not to download the same archive again and again.
