### ISSUE TITLE
issue with flutter master channel

### ISSUE THREAD

**Issue by raldhafiri** [espresso3389/pdfrx#156]
I have tried the package with latest flutter master and failed to compile for function `dispatchSelectionEvent` on `lib/src/widgets/pdf_page_text_overlay.dart`

I found that they have introduced `SelectionEventType.selectParagraph` .. is to possible to add `default` case for `switch(event.type)` .. it will solve the issue for current master

I know its still not stable release but just want to highlight an issue that could be avoided once its pushed to beta and stable

**Comment by espresso3389** [comment]
Could you please create a PR for this?
Basically I'll accept PRs that is working with current stable but your suggestion seems OK.

**Comment by espresso3389** [comment]
1.0.63 contains the fix.
