### ISSUE TITLE
Build Errors with AGP 8.6 and NDK 26.1.10909125 on Android Project

### ISSUE THREAD

**Issue by FranGonzalezAnleo** [espresso3389/pdfrx#158]
### Environment
- **Flutter**: 3.19.6
- **Android Gradle Plugin (AGP) Version**: 8.6
- **Pdfrx**: 1.0.63
- **NDK Version**: 26.1.10909125
- **minSdkVersion**: 23

### Issue Description
Attempting to build an Android project using AGP 8.6 with the specified NDK version results in configuration errors. Below are the details of the issues encountered during the build process.

### Errors

> [CXX1110] Platform version 19 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.

> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@1bd19362 of type BuildFlowService.Parameters
> A problem occurred configuring project ':pdfrx'.
> [CXX1110] Platform version 19 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.

### Additional Information
- Detailed information about changes in the NDK can be found in the [NDK Changelog](https://github.com/android/ndk/wiki/Changelog-r26).

### Steps to Reproduce
1. Set up an Android project with the specified AGP and NDK versions.
2. Configure minSdkVersion to 21 or higher in the Android manifest.
3. Attempt to build the project.

### Expected Outcome
Successfully configure and build the project without encountering the above errors.

### Actual Outcome
Build fails with errors regarding unsupported platform version and problems querying property values.

### Workaround
Adding `android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21` in the Gradle build file allows the project to build successfully, despite the plugin version being below the recommended level.

**Comment by espresso3389** [comment]
@FranGonzalezAnleo 8b04c2f15d5d841802adfc27c22298a0859d285b changes `minSdkVersion` to 21. Could you please check whether the change fixes your issue?

**Comment by FranGonzalezAnleo** [comment]
Hi @espresso3389  thakns for u great job!

yes with this change it works! I think the issue is related with the NDK that it is going to set the one from the SDK although.

In the documentation u can check that KitKat is not supported in the upcomming Flutter version (3.22.0)

I should have created a PR directly but changing the minSDK could be a breaking change for some people.

**Comment by espresso3389** [comment]
In the current situation, PDFium requires minSdkVersion=21 so it's completely OK for pdfrx.
