### ISSUE TITLE
run example code questions

### ISSUE THREAD

**Issue by jhmarryme** [espresso3389/pdfrx#16]
hello, I saw the readme document saying that pdfrx is a PDF viewer implementation built on the top of pdfium.

I have never used pdfium and I don’t quite understand what it is. Do I need to do anything?

When I run the example code(Flutter 3.16.3), it works normally on the web side, but cannot be used on windows. The prompt is as follows,Thanks

CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:53 (file):
  file COPY cannot find
  "E:/code/pdfrx/example/build/windows/x64/pdfium/chromium%2F6124/bin/pdfium.dll":
  No error.

CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:57 (file):
  file COPY cannot find
  "E:/code/pdfrx/example/build/windows/x64/pdfium/chromium%2F6124/lib/pdfium.dll.lib":
  No error.

CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:62 (file):
  file COPY cannot find
  "E:/code/pdfrx/example/build/windows/x64/pdfium/chromium%2F6124/include":
  No error.

​

**Comment by jhmarryme77777** [comment]
I found that you specified the download address of pdfium-binaries in CMakeLists.txt, but / failed to encode it correctly, causing me to be unable to download it correctly. Can you modify it?

```
set(PDFIUM_BINARY_RELEASE chromium%2F6124)

```

**Comment by jhmarryme** [comment]
I found that you specified the download address of pdfium-binaries in CMakeLists.txt, but / failed to encode it correctly, causing me to be unable to download it correctly. Can you modify it?
```
set(PDFIUM_BINARY_RELEASE chromium%2F6124)
```

**Comment by espresso3389** [comment]
Strangely enough, if I build Windows version with the fresh git cloned code, the example code builds and runs correctly:

<img width="639" alt="image" src="https://github.com/espresso3389/pdfrx/assets/1311400/dbfe6bc2-855a-4447-a504-38792c9d4599">

Which version of pdfrx are you using? Could you please use the latest (0.3.6) version?

**Comment by jhmarryme** [comment]
thank you for your reply! 
I tried version 0.3.6 again, but I still found that I could not download the tgz package of pdfium, and the final downloaded package was 0kb.
I don't know if it's my problem


```

❯ ll
total 0
-rw-r--r-- 1 jhmarryme jhmarryme 0 Jan  5 14:40 pdfium-linux-x64.tgz
~/d/c/f/flutter-examples/f/t/build/linux/x64/debug/pdfium/chromium%2F6124 dev_in_action *1 +1 !1 ?1                                                                                                                                                                                                          14:43:14
❯ 

```

**Comment by jhmarryme** [comment]
> Strangely enough, if I build Windows version with the fresh git cloned code, the example code builds and runs correctly:
> 
> ![image](https://private-user-images.githubusercontent.com/1311400/294409856-0e5482ff-b463-4536-b918-85c4847310c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzczNTAsIm5iZiI6MTcwNDQzNzA1MCwicGF0aCI6Ii8xMzExNDAwLzI5NDQwOTg1Ni0wZTU0ODJmZi1iNDYzLTQ1MzYtYjkxOC04NWM0ODQ3MzEwYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDY0NDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MzYjI0OTBlZDMzODA4MTdhMmNiM2VjYjNjNGQzOGY5YmNlMGY5ZjYwNjJlNjI0MGZjNTlhMTIwOWQ4ZmM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tc64R8cemmPqHn0sg1PRO11qU6QYVsT5Rbs230sfAt4)
> 
> Which version of pdfrx are you using? Could you please use the latest (0.3.6) version?

thank you for your reply!
I tried version 0.3.6 again, but I still found that I could not download the tgz package of pdfium, and the final downloaded package was 0kb.
I don't know if it's my problem

```
❯ ll
total 0
-rw-r--r-- 1 jhmarryme jhmarryme 0 Jan  5 14:40 pdfium-linux-x64.tgz
~/d/c/f/flutter-examples/f/t/build/linux/x64/debug/pdfium/chromium%2F6124                                                                                                                                                                                                14:43:14
❯ 
```

**Comment by espresso3389** [comment]
@jhmarryme Are you behind some HTTP proxy or such?

I suspect that some proxy might block downloading binary from: https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F6124/pdfium-windows-x64.tgz

Can you download the binary using browser?

**Comment by jhmarryme** [comment]
@espresso3389 I can download it directly through the browser or through the wget command. I began to suspect that this is a problem with my own computer. Thank you again for your reply!

**Comment by espresso3389** [comment]
Even in case downloading is not working correctly, you can download the binaries manually and place them on the build directories such as `build/windows/x64/pdfium/chromium%2F6124` and then do `flutter run` or something will continue the build process.

**Comment by jhmarryme** [comment]
thanks , it did work

**Comment by espresso3389** [comment]
@mlican
Your issue seems same to the issue.
Please check the contents of directory: `pdfrx/android/.cxx/Debug/<something>/armeabi-v7a/pdfium/chromium%2F6150`.

If the download succeeded, the directory contains the following files/directories:
```
LICENSE
PDFiumConfig.cmake
VERSION
args.gn
include
lib
pdfium-android-arm.tgz
```

If you miss some of them, then, check your build log (using command like `flutter build apk --release --verbose`) whether downloading was failed or not.
