### ISSUE TITLE
PDF Loading time too much long for big size pdf 

### ISSUE THREAD

**Issue by 90tamal90** [espresso3389/pdfrx#161]
When open a big size pdfs , like 500 pages pdf ....then the pdf loading time of too much ...... and memory consumption is too much ....please help me 🙏....

1. I think here all pages are rendered at same time .....if per page render when scrolling ....
2. How to implement the loading indicator per page ??

**Comment by espresso3389** [comment]
> I think here all pages are rendered at same time .....if per page render when scrolling ....

No, the rendering is per-page basis.
The problem seems in the page layout logic. It firstly calculates the width/height of all the pages.

I've tested pdfrx with large documents like [PDF Reference](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf) and the loading speed is acceptable even if we dynamically download it.

So if your 500-page document takes so long time, the PDF file's structure is too much complicated. Without the file, we cannot check the actual issue.

If you're just talking about download progress, [here](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#loading-indicator) it is.

And, the memory consumption is already optimized on the latest version. I think there's already no room to optimize the memory usage on pdfrx. If you need more optimization, we should do some in pdfium.

**Comment by 90tamal90** [comment]
1. I am talking about when the pdf render per page ...then the circular progress indicator (Not download indicator) appear in per page ....actually, here the page sometimes blank ....then the pdf show ...

2. You told "The problem seems in the page layout logic. It firstly calculates the width/height of all the pages." -------> how to overcome .....here the app sometimes completely freezed 

3. How to double tap to zoom fuction ??? 

4. I implement the code of fetch total pages count ....Future<void> _fetchTotalPages() async {
    final document = await PdfDocument.openFile(widget.pdfPath!);

    ///To prevent the memory leak
    if(mounted) {
      setState(() {
        List<PdfPage> pages = document.pages;

        _totalPages = pages.length;
      });
    }

  }  ....

5. I want to implement the vertical and horizontal mode with a button ... here i want to see this in realtime so i implement " forceReload: isReloadPDFView,"  option ...but then the pdf pages are not fit in the layout ...until when touched the screen .. =============> Here my method of vertical/ horizontal .....code.......

layoutPages: (pages, params) {

                  if (!isHorizontalViewMode) {
                    // Vertical layout (default)
                    final width = pages.fold(0.0, (prev, page) => max(prev, page.width));
                    final pageLayouts = <Rect>[];
                    double y = params.margin;
                    for (final page in pages) {
                      final height = page.height * (width / page.width);
                      pageLayouts.add(
                        Rect.fromLTWH(
                          params.margin,
                          y,
                          width,
                          height,
                        ),
                      );
                      y += height + params.margin;
                    }
                    return PdfPageLayout(
                      pageLayouts: pageLayouts,
                      documentSize: Size(width + params.margin * 2, y),
                    );
                  } else {
                    // Horizontal layout
                    final height = pages.fold(0.0, (prev, page) => max(prev, page.height)) + params.margin * 2;
                    final pageLayouts = <Rect>[];
                    double x = params.margin;
                    for (var page in pages) {
                      pageLayouts.add(
                        Rect.fromLTWH(
                          x,
                          (height - page.height) / 2, // center vertically
                          page.width,
                          page.height,
                        ),
                      );
                      x += page.width + params.margin;
                    }
                    return PdfPageLayout(
                      pageLayouts: pageLayouts,
                      documentSize: Size(x, height),
                    );
                  }

            },

**Comment by lin1270** [comment]
300 pages... 3-5seconds.

**Comment by espresso3389** [comment]
Please don't reuse a single issue for many things.
I ignore all your questions on the issue.

**Comment by espresso3389** [comment]
I think it's quite normal to load 300 pages in 3-5 seconds. Only your issue is it just freezing before showing the pages. I understand your pain. But I'm still thinking how to do that...

**Comment by letrungdo** [comment]
@espresso3389 I think this could be the solution: https://apryse.com/blog/pdf-format/what-is-pdf-linearization
https://github.com/mozilla/pdf.js/issues/8897

**Comment by espresso3389** [comment]
@letrungdo pdfrx uses pdf.js for web version so `PDFJS.disableAutoFetch` might be an option though I think it does not work for the case.

By the way, why are you referencing PDF linearization here?

**Comment by letrungdo** [comment]
@espresso3389 PDF linearization I think for pdf files downloaded from url it will be necessary to download the first pages to display first, not having to wait for the file to finish downloading to display.

**Comment by espresso3389** [comment]
@letrungdo PDF linearization is how PDF content should be and it has nothing to do with PDF viewer.

**Comment by lin1270** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
