### ISSUE TITLE
Does it have abillity to render custom widgets inside PdfLayout?

### ISSUE THREAD

**Issue by TarasBounty** [espresso3389/pdfrx#17]
For example I need to show text at the bottom of all pdf pages. 
User scrolls to the end and see some Widget (text, container, checkbox etc.)

**Comment by espresso3389** [comment]
Good question, it is temporary removed on [0.3.4](https://github.com/espresso3389/pdfrx/blob/master/CHANGELOG.md#034) and later due to internal structure change.
It will be soon back. Please wait just one or two days (I'm now working on it).

**Comment by espresso3389** [comment]
[0.4.2's README](https://pub.dev/packages/pdfrx/versions/0.4.2#adding-page-number-on-page-bottom) explains how to do that.

```dart
pageOverlayBuilder: (context, pageRect, page) {
  return Align(
    alignment: Alignment.bottomCenter,
    child: Text(page.pageNumber.toString(),
    style: const TextStyle(color: Colors.red)));
},
```

**Comment by TarasBounty** [comment]
> [0.4.2's README](https://pub.dev/packages/pdfrx/versions/0.4.2#adding-page-number-on-page-bottom) explains how to do that.
> 
> ```dart
> pageOverlayBuilder: (context, pageRect, page) {
>   return Align(
>     alignment: Alignment.bottomCenter,
>     child: Text(page.pageNumber.toString(),
>     style: const TextStyle(color: Colors.red)));
> },
> ```

Thank you! Works perfect!
