### ISSUE TITLE
RTL (Right-to-Left) reading order for Old Chinese Books

### ISSUE THREAD

**Issue by lin1270** [espresso3389/pdfrx#171]
I want to render Chinese old books which use rtl mode.
So..how could i do.

**Comment by espresso3389** [comment]
There already PdfViewerController and you can controll zoom programatically.
What do you want?

**Comment by lin1270** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by lin1270** [comment]
I want pdfrx to controll the common things. such as zoom, go page.
so I just need to handle render things.

**Comment by espresso3389** [comment]
They're already there. Please read [README.md](https://github.com/espresso3389/pdfrx/blob/master/README.md).

**Comment by lin1270** [comment]
I want to render Chinese old books which use rtl mode.
So..how could i do.

**Comment by espresso3389** [comment]
pdfrx still does not have enough controll for page snapping or such.
But if you want to do horizontal scrolling, see [Horizontal Scroll View](https://github.com/espresso3389/pdfrx/blob/master/README.md#horizontal-scroll-view).

Basically, for R-to-L reading order, you may change the layout logic to run oppsite order.

```dart
layoutPages: (pages, params) {
  final height =
      pages.fold(0.0, (prev, page) => max(prev, page.height)) +
          params.margin * 2;
  final width = pages.fold(params.margin * 2, (prev, page) => prev + page.width;
  final pageLayouts = <Rect>[];
  double x = width;
  for (var page in pages) {
    x -= page.width + params.margin;
    pageLayouts.add(
      Rect.fromLTWH(
        x,
        (height - page.height) / 2, // center vertically
        page.width,
        page.height,
      ),
    );
  }
  return PdfPageLayout(
    pageLayouts: pageLayouts,
    documentSize: Size(width, height),
  );
},
```

Disclaimer: I've not tested the code :(
