### ISSUE TITLE
pod install failed on mac os

### ISSUE THREAD

**Issue by lin1270** [espresso3389/pdfrx#173]
pedding on:
Installing pdfrx (0.0.1)

mac version:
M2. 
14.4.1

**Comment by espresso3389** [comment]
Could you give me more detail about your failure? such as the logs from `flutter build <something> --verbose` and `flutter doctor -v` ?

**Comment by lin1270** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by lin1270** [comment]
<img width="994" alt="image" src="https://github.com/espresso3389/pdfrx/assets/44795059/7cfd38e3-662a-4470-accb-807e27cec6ca">

**Comment by lin1270** [comment]
Timeout...
It took too long.

**Comment by espresso3389** [comment]
I guess you're in China and access to github releases are blocked by GFW.
So, if only the releases are the cause of problems, I can introduce some mechanism to switch the URL to other (by introducing some environment variable); I mean you somehow manually downloads these files and then host them on somewhere on your side and then the script runs without such blocking issues...

I don't know about your situation but if you have any such realistic suggestion, please ask me anything.
