### ISSUE TITLE
Small Page Size PDF Not Scaling to Fit Screen

### ISSUE THREAD

**Issue by enoiu** [espresso3389/pdfrx#174]
Thank you for creating this wonderful package.

I am using `PdfDocumentViewBuilder` and `PdfPageView`, but I noticed that a certain PDF file does not scale to fit the screen.
Below is a minimal example.
Is this the intended behavior?

<details>
<summary>Image</summary>

| Expected Result | Actual Result |
| ---- | ---- |
| ![Simulator Screenshot - iPad (10th generation) - 2024-06-17 at 16 05 25](https://github.com/espresso3389/pdfrx/assets/69666654/054a509a-36b4-4856-ad3c-b646d384f468) | ![Simulator Screenshot - iPad (10th generation) - 2024-06-17 at 16 04 17](https://github.com/espresso3389/pdfrx/assets/69666654/7cc33e84-7d2b-43de-ab9e-1cf3f1e9ed96) |

</details>

<details>
<summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:pdfrx/pdfrx.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: PdfDocumentViewBuilder.asset(
        'assets/sample2.pdf',
        builder: (context, document) {
          return PdfPageView(
            document: document,
            pageNumber: 1,
          );
        },
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79
    darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Additional Information**
- The Expected Result uses `maximumDpi: 450,` in the `PdfPageView`.
- This PDF file was downloaded from [here](https://imslp.org/wiki/Special:ReverseLookup/51970).
- This issue has been observed on both Android and iOS.
- pdfrx version is 1.0.68

**Comment by espresso3389** [comment]
I could not download the PDF anyway...

**Comment by espresso3389** [comment]
Ah, I found if the screen size is larger than 300 dpi, the page image may be rendered smaller than the page placeholder :(

**Comment by espresso3389** [comment]
1.0.69 contains the fix.

**Comment by enoiu** [comment]
Thank you for your response.
After updating to version 1.0.69, the PDF is now properly scaled to fit the screen.

Thank you for your great work!
