### ISSUE TITLE
PDF doesn't pan nor zoom when opened in browser on mobile devices

### ISSUE THREAD

**Issue by RustamG** [espresso3389/pdfrx#180]
pdfrx version: 0.4.54

### Steps to reproduce
1. Open https://espresso3389.github.io/pdfrx/ in a browser on Android or iOS device
2. Try to scroll or zoom-in using gesture

### Actual result
Nothing happens

### Expected result
The PDF can scroll and zoom using touch gestures

**Comment by espresso3389** [comment]
Text selection affects pan/zooming feature on Flutter Web on mobile devices.
So, just set `enableTextSelection: false` will enable pan/zooming.
This is just a limitation of the current "experimental" text selection feature (Related: #4).

**Comment by espresso3389** [comment]
[[CHANGELOG: 0.4.7]](https://github.com/espresso3389/pdfrx/blob/dfb929b73852910690261098c231800978177e0f/CHANGELOG.md#047) already mentioned the issue anyway.
