### ISSUE TITLE
The margin parameter is no longer respected by PdfViewerController.ensureVisible()?

### ISSUE THREAD

**Issue by koichia** [espresso3389/pdfrx#181]
Hello,

It appears that the latest pdfrx build no longer respects the margin parameter for PdfViewerController.ensureVisible()?

It could be due to this commit from last week?
https://github.com/espresso3389/pdfrx/commit/4769441fe261ac5293c61f8c835110e0868dcf2a#diff-df3d573f70e88b8abb45aa7771fb9420aa7767e875e9678a6f0b64044adf2b4cR1369

where it used to be
```
_state._calcMatrixToEnsureRectVisible(rect, margin: margin);
```
but now its
```
_calcMatrixToEnsureRectVisible(rect),
```

For now I workaround it in my code by doing `ensureVisible(rect.inflate(margin))`.

Anyway, thank you for the fantastic plugin!
Koichi

**Comment by espresso3389** [comment]
1.0.70 contains a fix for the issue.

**Comment by koichia** [comment]
Great, thank you!
