### ISSUE TITLE
Loading PDF with cookies

### ISSUE THREAD

**Issue by IchordeDionysos** [espresso3389/pdfrx#182]
Hey,

We've seen there is a property `withCredentials` that allows us to configure whether to send Cookies with the request or not.
https://github.com/espresso3389/pdfrx/blob/fdc10211c0799d6d0d49ac831776874d8aafee35/lib/src/web/pdf.js.dart#L41

There seems to be no way to set `withCredentials` to true from `PDFViewer.uri()`.

Any insights how we could achieve this?

**Comment by espresso3389** [comment]
1.0.71 contains the fix.

**Comment by IchordeDionysos** [comment]
Thanks @espresso3389 for the quick resolution 😍 I do appreciate it
