### ISSUE TITLE
PDF page not going to perticular page in GoToPage option

### ISSUE THREAD

**Issue by 90tamal90** [espresso3389/pdfrx#186]
when put the specific page in goToPage ....it is not going to the specific page number .....

  Future<void> _scrollToPage(int page) async {
    
      await controller.goToPage(pageNumber: page );
  
      // controller.setCurrentPageNumber(page);
    }

**Comment by lin1270** [comment]
fixed:
duration: Duration.zero

**Comment by 90tamal90** [comment]
Where I put this code ???

**Comment by 90tamal90** [comment]
Thanks 🙏🧑‍💻
