### ISSUE TITLE
 Pdf view is not fit in the view when call forceReload

### ISSUE THREAD

**Issue by 90tamal90** [espresso3389/pdfrx#187]
When call the forceRelod .....then pdf page is not fit in the view .........I notice when the page number is 2nd page or next .....then pdf view is not fit ..... 

Here I want to change horizontal and vertical view press button ...then reload the pdf view ..

**Comment by espresso3389** [comment]
Could you please explain me what is "force reload"?

**Comment by 90tamal90** [comment]
Sir basically, when horizontal and vertical PDF views change with a button in real-time...then I use the force reload feature....
here my code ....
    
    ///------------Dynamically calculate the page viewport and number----------///
              calculateCurrentPageNumber: (viewport, pageLayouts, controller) {
                if (isHorizontalViewMode) {
                  // Manually calculate the current page number in horizontal mode
                  final double viewportCenter =
                      viewport.left + viewport.width / 2;
                  double minDistance = double.infinity;
                  int currentPageNumber = 1;

                  for (int i = 0; i < pageLayouts.length; i++) {
                    final pageLayout = pageLayouts[i];
                    final centerDistance =
                        (viewportCenter - pageLayout.center.dx).abs();

                    if (centerDistance < minDistance) {
                      minDistance = centerDistance;
                      currentPageNumber = i + 1; // Page numbers are 1-based
                    }
                  }

                  return currentPageNumber;
                } else {
                  // In vertical mode
                  if (pageLayouts.isEmpty) {
                    // Handle the case when there are no page layouts (e.g., empty PDF)
                    return 1;   // Or any other appropriate value
                  }
                  
                  final viewportCenter = viewport.top + viewport.height / 2;
                  double maxVisibleArea = 0;
                  int currentPageNumber = 0;

                  for (int i = 0; i < pageLayouts.length; i++) {
                    final pageLayout = pageLayouts[i];
                    final visibleArea =
                        viewport.intersect(pageLayout).height * viewport.width;
                    final centerDistance =
                        (viewportCenter - pageLayout.center.dy).abs();

                    // Adjust weights based on your requirements
                    final score = visibleArea + centerDistance * 0.5;

                    if (score > maxVisibleArea) {
                      maxVisibleArea = score;
                      currentPageNumber = i + 1; // Page numbers are 1-based
                    }
                  }

                  return currentPageNumber;
                }
              },


and in   PdfViewerParams ....

        
            
              forceReload: isReloadPDFView,
              pageAnchor: PdfPageAnchor.top,
              pageAnchorEnd: PdfPageAnchor.bottom,




https://github.com/espresso3389/pdfrx/assets/170789007/e17008a6-6355-431c-b83d-5474ad8b8942

**Comment by espresso3389** [comment]
OK, the control of the view is not automatic because basically we cannot know your intention; in other words, we don't know what should be the default behavior.

So, it's completely up to you to control the behavior. You'd better call PdfViewController.goToXXX to control the current page.

**Comment by 90tamal90** [comment]
Ok....thanks

**Comment by espresso3389** [comment]
Any further questions or comments?

**Comment by 90tamal90** [comment]
No, Sir... I have implemented PdfViewController.goToXXX when calling horizontal and vertical views....

But, if there is a feature like "pdfview.horizontal(true)" .....by default...then it is quite helpful
