### ISSUE TITLE
Do not automatically zoom when scale is small

### ISSUE THREAD

**Issue by lin1270** [espresso3389/pdfrx#188]
I hope it can be completely controlled by the user for scaling, without automatic scaling

**Comment by espresso3389** [comment]
Basically, there several things to do:

- On `PdfViewer.something` set the following parameters
  - `useAlternativeFitScaleAsMinScale: false`,
  - `pageAnchor: PdfPageAnchor.topCenter`,
  - `pageAnchorEnd: PdfPageAnchor.bottomCenter`,
  - `minScale`

And, on every `goToPage` calls, set `anchor: PdfPageAnchor.topCenter` or such to not change zoom ratio on move.

Of course, `topCenter` can be `bottomCenter` or such to change behavior to what you want.
