### ISSUE TITLE
Digital Signature fields are not visible on non-Web platforms

### ISSUE THREAD

**Issue by cyberneid** [espresso3389/pdfrx#19]
Digital Signature fields are not visible on Windows, with the same issues as on Android.

In Web platform, that uses pdf.js instead of pdfium, digital signature fields are visible.

**Comment by espresso3389** [comment]
[0.4.1](https://pub.dev/packages/pdfrx/versions/0.4.1) introduces `PdfViewerParams.enableRenderAnnotations` to control the visibility of PDF annotations on pages.

The following fragment illustrates the typical usage:

```dart
PdfViewer.asset(
  'assets/hello2.pdf',
  displayParams: PdfViewerParams(
    enableRenderAnnotations: true,
  ),
),       
```

**Comment by cyberneid** [comment]
I'm sorry. Just tried on Windows and Android but it doesn't work.
Try with the following signed pdf.

[sample3.pdf](https://github.com/espresso3389/pdfrx/files/13850130/sample3.pdf)

**Comment by espresso3389** [comment]
Ah, signatures are not annotations... OK, need more work for that :(

**Comment by cyberneid** [comment]
Yes, exactly. signatures are a special type of annotation.
Consider that AndroidPdfViewer, which uses pdfium too, works like a charm with signatures:
https://github.com/barteksc/AndroidPdfViewer

**Comment by espresso3389** [comment]
[0.4.4](https://pub.dev/packages/pdfrx/versions/0.4.4) changed the parameter to control the annotation rendering mode:

```dart
PdfViewer.asset(
  'assets/hello2.pdf',
  displayParams: PdfViewerParams(
    annotationRenderingMode: PdfAnnotationRenderingMode.annotationAndForms,
  ),
),       
```

**Comment by liquidiert** [comment]
Sorry to comment on an old issue but I can't get any form to render on linux. Any help on how to debug / provide a traceback would be appreciated @espresso3389 !
