### ISSUE TITLE
Smooth Scroll feature in pdfview 

### ISSUE THREAD

**Issue by 90tamal90** [espresso3389/pdfrx#192]
How to scroll smoothly in PDF view ?? 
here the PDF view scrolls like page by page type ....not too smooth ...

But with scrollbar it is perfectly fine .

**Comment by espresso3389** [comment]
Scroll page by page is implemented by PdfViewerController.goToPage.
And, the parameter named `anchor` controls how to fit the page. Use PdfPageAnchor.topCenter or such to change page without changing the zoom for page fit.
