### ISSUE TITLE
Extract text

### ISSUE THREAD

**Issue by 4-alok** [espresso3389/pdfrx#195]
Is there any way to extract text by page?

**Comment by espresso3389** [comment]
- Open PdfDocument using one of [PdfDocument.openXxxx methods](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocument-class.html#static-methods)
- [Get page](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocument/pages.html)
- Load text using [PdfPage.loadText](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPage/loadText.html)
- Use [PdfPageText methods](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageText-class.html)
