### ISSUE TITLE
Archive member invalid control bits : pdfrx: ^1.0.74

### ISSUE THREAD

**Issue by reddeath1** [espresso3389/pdfrx#199]
Failed to build iOS app
Error (Xcode): Archive member invalid control bits in '/Volumes/Reddeaths/SERVER/www/PROJECTS/APPS/mwanaclick/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/pdfrx/libpdfium.a'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Error (Xcode): Unknown file type in '/Volumes/Reddeaths/SERVER/www/PROJECTS/APPS/mwanaclick/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/pdfrx/libpdfium.a'

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

**Comment by espresso3389** [comment]
Could you give me `flutter doctor -v`?

**Comment by espresso3389** [comment]
I never know about "Error (Xcode): Archive member invalid control bits in...". Just googling it does not show me anything about the error. But I'm guessing that the archive is broken in someway.

So please firstly clean your develop environment  (I don't know what to clean anyway; may be deleting all of pub_cache and then run `flutter clean`??) and retry to build.

**Comment by reddeath1** [comment]
Flutter clean, cleaned that error but now 

Lexical or Preprocessor Issue (Xcode): 'fpdfview.h' file not found
/Users/reddeath/.pub-cache/hosted/pub.dev/pdfrx-1.0.74/src/pdfium_interop.cpp:4:9

I guess I should delete the file and pod install again. 

ON Android it works fine.

**Comment by espresso3389** [comment]
In typical situation, fpdfview.h is placed there:

`/Users/reddeath/.pub-cache/hosted/pub.dev/pdfrx-1.0.74/darwin/pdfium/.lib/pdfium-apple-v9/ios/pdfium.xcframework/ios-arm64/Headers/fpdfview.h`

![image](https://github.com/espresso3389/pdfrx/assets/1311400/176d2ea0-7c1c-4521-a527-b46d89f2fd03)

Do you see the file?

You'd better clean `/Users/reddeath/.pub-cache/hosted/pub.dev/pdfrx-1.0.74` directory also.

**Comment by reddeath1** [comment]
After clean up in both flutter build and pub_cache iOS works now.. thank you

**Comment by aqueebqazi** [comment]
this helped me so thanks
