### ISSUE TITLE
Quality loss on zoom

### ISSUE THREAD

**Issue by reddeath1** [espresso3389/pdfrx#200]
Hi on version 1.0.65 you can zoom to 0 pixel without losing any quality but now on latest version when you zoom is as if your zooming an image.

what could be the issue.

**Comment by espresso3389** [comment]
Sorry, but could you explain your issue in other words? I cannot understand what you're saying.

**Comment by espresso3389** [comment]
What device are you using?

One of possible cause of the pixelation is out of memory. Or some kind of slow image processing.

And, do you see any exception or errors shown in debug console?

**Comment by reddeath1** [comment]
I m using Samsung S21 ultra, memory and storage is not the issue because it's just a testing device so everything is at 10%.

**Comment by reddeath1** [comment]
But the issue is before it was doing well on version 1.0.65

**Comment by espresso3389** [comment]
I'm testing pdfrx on slow devices but they do not behave like that.

According to the CHANGELOG, there are several changes that affects the rendering behaviors:

### 1.0.59

- Fixes concurrency issue on PdfDocument dispose (#143)

### 1.0.58

- Any API calls that wraps pdfium are now completely synchronized. They are run in an app-wide single worker isolate
  - This is because pdfium does not support any kind of concurrency and even different PdfDocument instances could not be called concurrently

### 1.0.57

- FIXED: possible double-dispose on race condition (#136)
- Add mechanism to cancel partial real size rendering (#137)

So could you try these versions 1.0.57, 1.0.58, 1.0.59, one by one to determine which version breaks your app's consistency?

**Comment by reddeath1** [comment]
This is how it behaves now.

`[](https://ibb.co/VYDCRBp)`

**Comment by espresso3389** [comment]
So, every versions works same way?

**Comment by reddeath1** [comment]
I just downgraded back to 1.0.65, I m solving some errors, I will update about this but since version 1 to 1.0.65 was fine until 1.0.65

**Comment by reddeath1** [comment]
Thank you again for providing such a good plugin. I downgraded to version 1.0.65, and it exhibited the same behavior. I then recalled removing a specific line of code earlier. After restoring that line, the plugin worked as intended.

It appears that the removed line was crucial for achieving the desired results. The page updates correctly when zoomed in, ensuring that the pixels are regenerated and the image quality is maintained.

I have updated to 1.0.74 and works as I needed to work.

```
layoutPages: (pages, params) {
                                  
>>> this line of code
> # if(!mounted){ 
>                                     setState(() {
>                                       totalPages = pages.length;
>                                     });
>                                   }
>>>
                                  final height = pages.fold(
                                          0.0,
                                          (prev, page) =>
                                              max(prev, page.height)) +
                                      params.margin * 2;
                                  final pageLayouts = <Rect>[];
                                  double x = params.margin;
                                  for (var page in pages) {
                                    pageLayouts.add(
                                      Rect.fromLTWH(
                                        x,
                                        (height - page.height) /
                                            2, // center vertically
                                        page.width,
                                        page.height,
                                      ),
                                    );
                                    x += page.width + params.margin;
                                  }

                                  return rx.PdfPageLayout(
                                    pageLayouts: pageLayouts,
                                    documentSize: ui.Size(x, height),
                                  );
                                },
```

**Comment by reddeath1** [comment]
> Thank you again for providing such a good plugin. I downgraded to version 1.0.65, and it exhibited the same behavior. I then recalled removing a specific line of code earlier. After restoring that line, the plugin worked as intended.
> 
> It appears that the removed line was crucial for achieving the desired results. The page updates correctly when zoomed in, ensuring that the pixels are regenerated and the image quality is maintained.
> 
> I have updated to 1.0.74 and works as I needed to work.
> 
> ```
> layoutPages: (pages, params) {
>                                   
> >>> this line of code
> > # if(!mounted){ 
> >                                     setState(() {
> >                                       totalPages = pages.length;
> >                                     });
> >                                   }
> >>>
>                                   final height = pages.fold(
>                                           0.0,
>                                           (prev, page) =>
>                                               max(prev, page.height)) +
>                                       params.margin * 2;
>                                   final pageLayouts = <Rect>[];
>                                   double x = params.margin;
>                                   for (var page in pages) {
>                                     pageLayouts.add(
>                                       Rect.fromLTWH(
>                                         x,
>                                         (height - page.height) /
>                                             2, // center vertically
>                                         page.width,
>                                         page.height,
>                                       ),
>                                     );
>                                     x += page.width + params.margin;
>                                   }
> 
>                                   return rx.PdfPageLayout(
>                                     pageLayouts: pageLayouts,
>                                     documentSize: ui.Size(x, height),
>                                   );
>                                 },
> ```

<a href="https://ibb.co/R9MfWnW"><img src="https://i.ibb.co/0cWT3N3/Simulator-Screen-Recording-i-Phone-15-Pro-Max-2024-07-03-at-23-02-55.gif" alt="Simulator-Screen-Recording-i-Phone-15-Pro-Max-2024-07-03-at-23-02-55" border="0"></a>

**Comment by espresso3389** [comment]
Ah, the behavior change is on [1.0.70](https://github.com/espresso3389/pdfrx/issues/9#issuecomment-1879735782)

1.0.70 calls re-layout logic on every zoom ratio changes to deal with #131.
Anyway, `layoutPages` should not call `setState` inside it. It must not have any kind of side effect except calculating page layout.

**Comment by reddeath1** [comment]
Thanks but removing that the behavi

**Comment by reddeath1** [comment]
> Ah, the behavior change is on [1.0.70](https://github.com/espresso3389/pdfrx/issues/9#issuecomment-1879735782)
> 
> 1.0.70 calls re-layout logic on every zoom ratio changes to deal with #131. Anyway, `layoutPages` should not call `setState` inside it. It must not have any kind of side effect except calculating page layout.

Thank you, I have rechecked the issue, seems your right 

I m using this code to update total pages for them to be displayed on the counter, when removing it, the zooming is fine but adding it is the problem.

Future.delayed(Duration.zero, ()=>setState(() {
                                    totalPages = pages.length;
                                  }));

**Comment by espresso3389** [comment]
Please note that `layoutPages` may be called several times during the page layout calculation and widget building process. So don't do anything except page layout.

To update number of pages, you can use [PdfViewerParams.onViewerReady](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/onViewerReady.html) or such.

**Comment by reddeath1** [comment]
> Please note that `layoutPages` may be called several times during the page layout calculation and widget building process. So don't do anything except page layout.
> 
> To update number of pages, you can use [PdfViewerParams.onViewerReady](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/onViewerReady.html) or such.

Thank you
