### ISSUE TITLE
FEATURE REQUEST: saveAsImageFile, saveAsImageData

### ISSUE THREAD

**Issue by akaita** [espresso3389/pdfrx#207]
Hi,

I'm still working out how to do some things, but great plugin so far. Thanks so much for your work! 

My usecase is that I have scanned pages in a pdf. If the users chooses to, I want to save one entire page as an image and apply transformations in it (with imagemagick, for example). 

Is it currently possible to open a pdf, choose one page, and save that one entire page as an image? 

If it is not possible, is it on the roadmap? 

Thanks again!

**Comment by espresso3389** [comment]
pdfrx currently does not have such direct methods to use.

But [PdfViewerController.useDocument](https://pub.dev/documentation/pdfrx/1.0.81/pdfrx/PdfViewerController/useDocument.html), which is introduced on 1.0.81, (or [PdfViewerController.document] can be used to access the [PdfDocument](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocument-class.html).

> [!NOTE]
> Of course, even before 1.0.81, you can use [PdfViewerController.document](https://pub.dev/documentation/pdfrx/1.0.81/pdfrx/PdfViewerController/document.html). But it is unsafe for long running asynchronous operation. You'd better use [PdfViewerController.documentRef](https://pub.dev/documentation/pdfrx/1.0.81/pdfrx/PdfViewerController/documentRef.html) for the safety but it's difficult to use. PdfViewerController.useDocument is a newer, safer, and, easier alternative recently introduced.

The following code illustrates how to get the [Image](https://api.flutter.dev/flutter/dart-ui/Image-class.html) from PdfViewerController though it omits `try-catch-finally` for ease of the code:

```dart
await controller?.useDocument((document) {
  final pdfImage = await document.pages[0].render();
  final image = pdfImage.createImage();
  
  // you can use image here

  image.dispose();
  pdfImage.dispose();
});
```

Or, [PdfImage](https://pub.dev/documentation/pdfrx/1.0.80/pdfrx/PdfImage-class.html) also have direct access to the raw image. Anyway, you can use such to save the image to file.

**Comment by espresso3389** [comment]
Are you only using PdfDocument?
In that case, the things get easier. Just use PdfImage.

**Comment by akaita** [comment]
Oh, this is brilliant. 
In my case I need to use PdfController to get the current page, so your code works great. 

I just added the fullWidth and fullHeight parameters to PdfImage.render(), because otherwise the image was very small. I want the user to be able to do zoom in the future, after I manipulate the image:

```
await _pdfViewerController.useDocument((document) async {
    final pdfImage = await document.pages[0].render(
        fullWidth: document.pages[0].width * 8,
        fullHeight: document.pages[0].height * 8);
    final image = await pdfImage?.createImage();

    // you can use image here

    image?.dispose();
    pdfImage?.dispose();
  },
);
```

Thank you so much 🙇
