### ISSUE TITLE
Render one page at a time (pageFling) instead of continuous rendering of pages

### ISSUE THREAD

**Issue by cyberneid** [espresso3389/pdfrx#21]
The current version renders the pages in continuous mode. i.e. you can have the bottom of page 1 above and the top of page 2 below. AndroidPdfViewer instead allows flinging a single page at a time (with pageFling property).

```
 /** Spacing between pages, in px */
    private int spacingPx = 0;

    /** Add dynamic spacing to fit each page separately on the screen. */
    private boolean autoSpacing = false;

    /** Fling a single page at a time */
    private boolean pageFling = true;
```

See this class: 
https://github.com/barteksc/AndroidPdfViewer/blob/master/android-pdf-viewer/src/main/java/com/github/barteksc/pdfviewer/PDFView.java

Can you add such a feature too?

**Comment by jezell** [comment]
Would be very useful for us, we used the pdf render textures from pdf_render for this, hard to switch over without something equivalent.

**Comment by espresso3389** [comment]
For Texture or such widget, I opened #41.

For page flinging, if I introduce some kind of Texture or such, I think [carousel_slider](https://pub.dev/packages/carousel_slider) or such is enough. Do you agree?

**Comment by cyberneid** [comment]
Yes carusel_slider may be a good option but with vertical scrolling

**Comment by espresso3389** [comment]
[0.4.23](https://pub.dev/packages/pdfrx/versions/0.4.23) introduces [PdfDocumentViewBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder-class.html) and [PdfPageView](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder-class.html).

@cyberneid 
PdfPageView can be used within other carousel like widget and I think it's enough for such use case.
Please check it and if you have any questions, please ask me!

**Comment by jezell** [comment]
@espresso3389 awesome!
