### ISSUE TITLE
Please update rxdart to rxdart: ^0.28.0 (latest version) to lift dependency constraint

### ISSUE THREAD

**Issue by stan-at-work** [espresso3389/pdfrx#211]
Can you please asap update rxdart:  to version ^0.28.0 now (rxdart ^0.27.7)

**Comment by espresso3389** [comment]
Other plugins still depend on rxdart 0.27.X and pdfrx could not break consistency with them.

Of couse you can use `dependency_overrides` to use 0.28.0; pdfrx does not have known compatibility issues with 0.28.X.

**Comment by stan-at-work** [comment]
> Other plugins still depend on rxdart 0.27.X and pdfrx could not break consistency with them.
> 
> Of couse you can use `dependency_overrides` to use 0.28.0; pdfrx does not have known compatibility issues with 0.28.X.

When will this be fixed ? override can't be a sustainable sulution...

**Comment by espresso3389** [comment]
I also want to know when.
No one explicitly or imlicitly say when but every plugin author thinks it is not today...
Whatever the future will be, we are only to use dependency_overrides.

**Comment by espresso3389** [comment]
Fixed on 96949ea (1.0.82).

**Comment by stan-at-work** [comment]
Thanks
