### ISSUE TITLE
UnknownErrorException: Failed to fetch

### ISSUE THREAD

**Issue by Yoda-Man** [espresso3389/pdfrx#213]
![image](https://github.com/user-attachments/assets/96dea387-77a9-4523-91ae-66829d6579e1)

**Comment by espresso3389** [comment]
On which platform? Also provide me with your `flutter doctor -v` or such.

**Comment by espresso3389** [comment]
Ah, `UnknownErrorException` is from PDF.js and "Failed to fetch" seems a very typical JS fetch error.
Please check your app's environment. It's not a pdfrx error but some of your app's deployment or configuration error.

**Comment by Yoda-Man** [comment]
ahh experimenting on web

**Comment by Yoda-Man** [comment]
ind@INDSRVFOG:~/Documents/Mobile/sc$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 22.04.4 LTS 6.5.0-44-generic, locale en_ZA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by espresso3389** [comment]
Some kind of CORS error or such?

**Comment by Yoda-Man** [comment]
> Some kind of CORS error or such?

https://d2pfzupyr45acp.cloudfront.net/1A80EA9F-9229-4240-9EC0-B1F08ECE051E/4de59457-513a-4df1-9424-7acc67cd2540.pdf this is the file I am trying to load its in an AWS S3 bucket

**Comment by espresso3389** [comment]
So did you configure CORS properly on the server?

**Comment by Yoda-Man** [comment]
> So did you configure CORS properly on the server?

you are correct just read an article on Configuring a CORS rule using the Amazon S3 console. It sorted the problem out
