### ISSUE TITLE
Form fields not visible in linux version

### ISSUE THREAD

**Issue by liquidiert** [espresso3389/pdfrx#214]
Hey! Very simple explanation: I can't get form fields and signature fields to show in linux. Any advice on how to debug this / provide further information would be appreciated!

**Comment by espresso3389** [comment]
Do you specify `PdfAnnotationRenderingMode.annotationAndForms` like this?

```dart
PdfViewer.asset(
  'assets/hello.pdf',
  params: PdfViewerParams(
    annotationRenderingMode: PdfAnnotationRenderingMode.annotationAndForms,
  ),
),
```

**Comment by espresso3389** [comment]
As far as I've tested, every platform including Linux shows signature fields correctly.

I found that you mentioned the issue [here](https://github.com/espresso3389/pdfrx/issues/19#issuecomment-2225799150) but did you test [the file](https://github.com/espresso3389/pdfrx/files/13850130/sample3.pdf)? I think pdfrx currently correctly show the stamp on the end of the document:

![image](https://github.com/user-attachments/assets/cab1684c-9cca-4fd2-8d94-74f02e9c369a)

Anyway, could you please provide me with some example PDF to know your issue?

**Comment by liquidiert** [comment]
Hey @espresso3389 Yeah tried it with your provided file but it does not show up. [Here](https://github.com/user-attachments/files/16315642/befreiung_ausweispflicht.pdf) is the one I tried. The forms don't show up for editing

**Comment by espresso3389** [comment]
> Hey @espresso3389 Yeah tried it with your provided file but it does not show up. [Here](https://github.com/user-attachments/files/16315642/befreiung_ausweispflicht.pdf) is the one I tried. The forms don't show up for editing

Oh, pdfrx does not support "editing" of forms. There are many things to do to support form editing.

**Comment by liquidiert** [comment]
@espresso3389 oh damn than I misunderstood that. My apologies!
