### ISSUE TITLE
CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:58 (file):

### ISSUE THREAD

**Issue by a13020796019** [espresso3389/pdfrx#216]
When I run Windows, I get an error message.I have tried before flutter clean & pub get，Still reporting the same error

Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:58 (file):
  file COPY cannot find
  "D:/soft/vscode/slider_app/build/windows/x64/pdfium/chromium%2F6555/bin/pdfium.dll":
  File exists.

CMake Error at flutter/ephemeral/.plugin_symlinks/pdfrx/windows/CMakeLists.txt:63 (file):
  file COPY cannot find
  "D:/soft/vscode/slider_app/build/windows/x64/pdfium/chromium%2F6555/include":
  File exists.

Error: Unable to generate build files

Exited (1).

**Comment by espresso3389** [comment]
I have completely no idea about the error. So do the files exist? The CMake message is already confusing...

By the way, did you enable Developer Mode on your mahcine?

**Comment by sumshare** [comment]
just download  [pdfium-win-x64.tgz](https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x64.tgz)
