### ISSUE TITLE
Android Build Error（Could not find Ninja on PATH or in SDK CMake bin folders.）

### ISSUE THREAD

**Issue by lq7y7-go** [espresso3389/pdfrx#218]
I was trying to build an Android project and after adding dependencies, an error occurred
![截屏2024-08-07 18 14 39](https://github.com/user-attachments/assets/6c7dc46b-fa0c-4ffb-b808-ce95f09721b0)
![截屏2024-08-07 18 15 52](https://github.com/user-attachments/assets/986e0709-ecd9-469c-9c0b-5ecffc490fc2)

**Comment by varun-tide** [comment]
@lq7y7-go how did you fix the issue?
