### ISSUE TITLE
'fpdfview.h ' file not found when i user Jenkins to create ios ipa

### ISSUE THREAD

**Issue by lq7y7-go** [espresso3389/pdfrx#219]
![截屏2024-08-09 16 52 08](https://github.com/user-attachments/assets/90a8baf6-4394-431a-a141-f96975ba7734)
pod --version 1.15.2

**Comment by espresso3389** [comment]
The same error was reported several times. I'm not sure about your Jenkins environment, but the possible solution to this is anyway deleting all the caches and build artifacts before building; `build/` and `.pub_cache`.

**Comment by espresso3389** [comment]
Duplicated: #138, #12
