### ISSUE TITLE
Support PDF.js legacy build

### ISSUE THREAD

**Issue by dorklein** [espresso3389/pdfrx#222]
PDF.js build uses moderen JavaScript and Browsers APIs.

To support older browser versions, PDF.js has a legacy build that includes pollyfils for newer APIs.

For example, when running `pdfrx` in Chome Version 109.0.5414.120 (Official Build) Windows 7 (same for Firefox)
I get an error:
`NoSuchMethodError: method not found: 'withResolvers' (Promise.withResolvers is not a function)`

![Crop image project Aug 11](https://github.com/user-attachments/assets/df7c62aa-fe9c-4995-ac6c-278de8ec5193)

**Comment by espresso3389** [comment]
Basically, we can use different version of pdf.js by setting [PdfJsConfiguration.configuration](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfJsConfiguration/configuration.html) before actual use (e.g. on the top of main function) of pdfrx.

**Comment by dorklein** [comment]
@espresso3389 Thanks for that.
