### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'fpdfview.h' file not found

### ISSUE THREAD

**Issue by zengchanghuan** [espresso3389/pdfrx#225]
Launching lib/ksmart/main.dart on iPad6 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: NJT84644HS
Running Xcode build...
Xcode build done.                                           25.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'fpdfview.h' file not found
/Users/zengchanghuan/.pub-cache/hosted/pub.flutter-io.cn/pdfrx-1.0.82/src/pdfium_interop.cpp:4:9

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Error launching application on iPad6.

flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (2 months ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by zengchanghuan** [comment]
When I use version 1.0.82, I keep reporting the above error, using 1.0.81 is fine.

**Comment by espresso3389** [comment]
Same issue is reported several times; #219, #199, #138, and #12.
Clear all the caches like `.pub_cache`, `build/` an d such (by `flutter clean`) may fix the issue.
