### ISSUE TITLE
PDF is blurry again

### ISSUE THREAD

**Issue by thomas4Bitcraft** [espresso3389/pdfrx#232]
I have the same problem again in the web - it was solved in a previous release.

I use version 1.0.83 currently

![image](https://github.com/user-attachments/assets/292ef768-9043-4964-8d5c-ce3b380b3935)

_Originally posted by @thomas4Bitcraft in https://github.com/espresso3389/pdfrx/issues/91#issuecomment-2345687383_

**Comment by MarcVanDaele90** [comment]
Same issue here; the text gets sharp after zooming in a few times, but becomes blurry again after zooming out
