### ISSUE TITLE
Loading state when using PdfDocumentViewBuilder

### ISSUE THREAD

**Issue by jamesldr** [espresso3389/pdfrx#233]
Do we have a way to verify the PDF is fully loaded when using `PdfDocumentViewBuilder.uri()`?

**Comment by espresso3389** [comment]
What do you mean by "PDF is fully loaded"?

**Comment by jamesldr** [comment]
I mean downloaded in that case, this is something that can be done by using the `PdfViewer.uri()` widget, but I couldn't find a way to do this on this one

**Comment by jamesldr** [comment]
I may have found an answer for my question... when PdfDocument is downloading, it's null on the builder. So might be able to check for that, I'm not sure if this is the only scenario that can cause a null for PdfDocument, does it throw an Excepction if download fail?

**Comment by espresso3389** [comment]
To handle document loading process, you'd better use [PdfDocumentRefUri](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentRefUri-class.html) directly:

```dart
final documentRef = PdfDocumentRefUri(Uri.parse('https://example.com/some/document.pdf'));
// Schedule downloading of the file immediately (Future.microtask is just an example use)
Future.microtask(() {
  // awaiting documentRef.load() ensures the downloading finished regardless of success or failure
  await documentRef.load();
  if (documentRef.error != null) {
    // error
  } else {
    // download success
  }
});

...

// It's OK to pass documentRef before download starts/ends
PdfViewer(documentRef, ...)
```

**Comment by gloinho** [comment]
Hi, i'm strugling loading a PDF from Uint8List. I'm trying to import PdfDocumentRefData, but I cant find the package. Any tips ?
