### ISSUE TITLE
Generation of a version 1.0.84

### ISSUE THREAD

**Issue by HeropolisDa2ny** [espresso3389/pdfrx#238]
Hello, sorry to bother again but is it possible to generate a version 1.0.84 please since the version 1.0.83 can produce a crash of the package and do not load anymore the PDFs ?

**Comment by espresso3389** [comment]
There two reasons block a new release of pdfrx:

- I'm just busy
- The master branch has on-going changes that cannot be released without further work

So, to release 10.0.84, we need to create some branch from 9f30d923d8e747d05 (1.0.83) and cherry-pick your fixes in some way (via PR or just cherry-picking the changes).

**Comment by espresso3389** [comment]
I just created a branch named [for_#230](https://github.com/espresso3389/pdfrx/tree/for_%23238) and will release a new version soon.

**Comment by espresso3389** [comment]
1.0.84 (84f476212ee74db8264ec0cb7d0fa0acea44ad0a) released.
