### ISSUE TITLE
Unable to Android Build On Linux

### ISSUE THREAD

**Issue by Yoda-Man** [espresso3389/pdfrx#243]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdfrx:buildCMakeRelWithDebInfo[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/android/.cxx/RelWithDebInfo/3j5c5v3g/arm64-v8a'
  [1/2] Building CXX object shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o
  FAILED: shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o 
  /home/ind/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/ind/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Dpdfrx_EXPORTS -I/home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/android/.lib/latest/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -MD -MT shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o -MF shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o.d -o shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o -c /home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/src/pdfium_interop.cpp
  In file included from /home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/src/pdfium_interop.cpp:2:
  In file included from /snap/flutter/current/usr/include/c++/9/thread:39:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /home/ind/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/android/.cxx/RelWithDebInfo/3j5c5v3g/arm64-v8a \
        pdfrx
    from /home/ind/.pub-cache/hosted/pub.dev/pdfrx-1.0.84/android
```

**Comment by espresso3389** [comment]
On my linux environment, `flutter build appbundle [--debug]` runs successfully with the following env:

```
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 5.15.153.1-microsoft-standard-WSL2, locale C.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] Connected device (2 available)
[✓] Network resources
```

Could you please show me your `flutter doctor` result?

**Comment by Yoda-Man** [comment]
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-45-generic, locale en_ZA.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/ind/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/ind/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /snap/android-studio/161/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /snap/android-studio/161
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Android Studio (version 2023.3)
    • Android Studio at /snap/android-studio/157
    • Flutter plugin version 80.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.93.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-45-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by Yoda-Man** [comment]
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-45-generic, locale en_ZA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.93.1)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by danallen88** [comment]
Running into the same issue here - any updates on this? It's because our CI is a linux box. I had no issues locally on macOS.

**Comment by espresso3389** [comment]
Many Flutter projects encounter the same issue and the only way to recover from the issue is re-installing Flutter and other tools. But no clear evidence.

https://www.google.com/search?q=%2Fsnap%2Fflutter%2Fcurrent%2Fusr%2Finclude%2Fc%2B%2B%2F9%2Fmemory%3A121%3A25%3A+error%3A+cast+from+pointer+to+smaller+type+%27uintptr_t%27+(aka+%27unsigned+int%27)+loses+information&oq=%2Fsnap%2Fflutter%2Fcurrent%2Fusr%2Finclude%2Fc%2B%2B%2F9%2Fmemory%3A121%3A25%3A+error%3A+cast+from+pointer+to+smaller+type+%27uintptr_t%27+(aka+%27unsigned+int%27)+loses+information
