### ISSUE TITLE
Android build broken? Cannot find libpdfium.so error

### ISSUE THREAD

**Issue by yhyh0** [espresso3389/pdfrx#25]
The Android example build from commit 706da7c72bd51a532ba487e580039b905441ea62 can't show any pdf. It sometimes gives 'null PdfViewerController' error, sometimes 'cannot find libpdfium.so dynamic lib' error. I checked, the .so libs are in the path like android/.cxx/Debug/2a416433/arm64-v8a/pdfium/chromium%2F6150/lib/${arch}.

But the old commit 286caf0efc48676827fb30376666a7fe8e242205 is fine.

Could it be that the following change causing it?

https://github.com/espresso3389/pdfrx/blob/8c5ddb3a3b16b2de37675a180b7766e6f0bff325/android/CMakeLists.txt#L34

**Comment by espresso3389** [comment]
FIXED on dd3c82ca48a065fa8dc2f8987e40ca8b7deae36c

**Comment by espresso3389** [comment]
[0.4.7](https://pub.dev/packages/pdfrx/versions/0.4.7) is released that contains the change.
