### ISSUE TITLE
onPageChanged is not triggered PdfViewerParams on some android devices

### ISSUE THREAD

**Issue by ahmadShehab0** [espresso3389/pdfrx#252]
I have this logic that users need to read the whole pdf document. In some devices I'm not able to track the page changed and the moved to a new page to activate the button and it's happening on some Android devices.

I was testing on Galaxy Z flip3.

![agremeent](https://github.com/user-attachments/assets/8fdbd3c5-1ab2-48a9-a48d-6b4a2fa42fdf)

**Comment by espresso3389** [comment]
onPageChaged is not reliable way to know the user read the document fully. It uses the amount of the screen space occupied by pages to know which page is the user's main concern... I don't have good word choise for this, main, current, or, anyway the page user is reading.

I think it's not the perfect algorithm but it's not easy to implement a perfect algorithm...

To know whether the user scrolls down to the end of document or not, you can use `PdfViewerController.visibleRect` and `PdfViewerController.documentSize`.

If `visibleRect.bottom` is identical to `documentSize`, it indicate the user reached the end.
You can check it on a listener function registered using `PdfViewerController.addListener`.
