### ISSUE TITLE
[FEATURE REQUEST] web 1.1.0 Support

### ISSUE THREAD

**Issue by Kuhlemann** [espresso3389/pdfrx#254]
Dependency constraints for package web 1.1.0 are not fulfilled, which blocks other package updates in my app.
Pdfrx is the only package in my app still constraining to 1.0.0, so I kindly ask to update to web 1.1.0-support.

> Because my_app depends on pdfrx ^1.0.87 which depends on web >=0.5.1 <1.1.0, web >=0.5.1 <1.1.0 is required.
> So, because my_app depends on web ^1.1.0, version solving failed.

P.S.: Good work with pdfrx, excellent package!

**Comment by espresso3389** [comment]
Supported on 1.0.89.
