### ISSUE TITLE
When build for Android and  last version of NDK

### ISSUE THREAD

**Issue by JgomesAT** [espresso3389/pdfrx#255]
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@17ac327a of type BuildFlowService.Parameters
   > A problem occurred configuring project ':pdfrx'.
      > [CXX1104] NDK from ndk.dir at /Users/jorgegomes/Library/Android/sdk/ndk/25.1.8937393 had version [25.1.8937393] which disagrees with android.ndkVersion [27.0.12077973]

**Comment by espresso3389** [comment]
Are you building pdfrx example? If so, it explicitly specify NDK 27.0.12077973 and you should install the NDK version; or you may change the NDK version on `example/viewer/android/app/build.gradle`.

If not so, please explain more about your project, including `flutter doctor` result.

**Comment by JgomesAT** [comment]
It's a tricky subject. If I change the NDK version in my build.gradle file to 27, I get some errors. If I set the NDK version to 27 in my local.properties file, I get different errors. I had to rollback to Gradle 7.6.5 (from 8.9) to get my build working again.

All this problem is happen when  I tried gradle 8.9

**Comment by espresso3389** [comment]
Gradle version is alway a headache and it kicks me almost once a week... And I don't know the right answer for the Gradle version :(

**Comment by JgomesAT** [comment]
I know, we can close the issue, thx
