### ISSUE TITLE
how to disable sliding Pdf page when i used PdfViewer.file?

### ISSUE THREAD

**Issue by paladinghub** [espresso3389/pdfrx#266]
thanks for your amazing lib.for some reason,i need disable sliding pages,how to do this

**Comment by espresso3389** [comment]
[PdfViewerParams](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams-class.html) has [panEnabled](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/panEnabled.html) and [scaleEnabled](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/scaleEnabled.html). Disable both to stop any page slidings by user interaction:

```dart
PdfViewer.file(
  ...
  params: PdfViewerParams(
    panEnabled: false,
    scaleEnabled: false,
    ...
  ),
),
```
