### ISSUE TITLE
Pdfrx negative space background colour

### ISSUE THREAD

**Issue by Nashwaay** [espresso3389/pdfrx#270]
Is there a way to change the background colour of this extra whitespace in grey colour to a different colour?
Or fit the pdf content to full container width?

![image](https://github.com/user-attachments/assets/862ee5c2-aeed-4fdd-9dc6-4ec18e5bf53c)

maxScale doesn't fulfill the purpose here

**Comment by espresso3389** [comment]
You can use [PdfViewerParams.backgroundColor](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/backgroundColor.html) to do that:

```dart
PdfViewer.file(....,
  params: PdfViewerParams(
    backgroundColor: Colors.blue,
    ...,
  ),
),
```
