### ISSUE TITLE
On Windows 11: FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Aiuspaktyn** [espresso3389/pdfrx#276]
A problem occurred configuring project ':pdfrx'.
> com.android.builder.errors.EvalIssueException: [CXX1101] NDK at C:\Users\X\AppData\Local\Android\sdk\ndk\27.0.12077973 did not have a source.properties file

**Comment by espresso3389** [comment]
Just install the NDK of the version shown in the error message.

FYI: [Install NDK and CMake automatically](https://developer.android.com/studio/projects/install-ndk) states that:
> Android Gradle Plugin 4.2.0+ can automatically install the required NDK and CMake the first time you build your project if their licenses have been accepted in advance. If you've already read and agree to the license terms, then you can pre-accept the licenses in scripts with the following command:

So, it seems all you have to do is `flutter doctor --android-licenses`.
