### ISSUE TITLE
gotoPage function does not work well

### ISSUE THREAD

**Issue by hnvmeta** [espresso3389/pdfrx#277]
I use `PdfViewer.file` to read a PDF file. When I call `controller.goToPage(pageNumber: page)` with `controller = PdfViewerController()`, the PDF Reader navigates to the wrong page.
You can see this bug in the attached video.

https://github.com/user-attachments/assets/1935504a-a8ac-42a6-865c-d070bcf6bb9c

**Comment by espresso3389** [comment]
Please describe your issue more precisely. It seems to be an Android but no code fragments, no technical background... At least, [the example viewer](https://espresso3389.github.io/pdfrx/) correctly works with goTo methods.

**Comment by hnvmeta** [comment]
Here are my code fragments:
` @override
  Widget build(BuildContext context) {
    var mode = context.watch<ThemeProvider>().themeMode;
    if (mode == ThemeMode.system) {
      if (Theme.of(context).brightness == Brightness.dark) {
        mode = ThemeMode.dark;
      } else {
        mode = ThemeMode.light;
      }
    }

    final darkMode = mode == ThemeMode.dark;
    var currentSpeechingPage = '';
    if (playingTtsFile != null) {
      currentSpeechingPage = '${playingTtsFile?.page}/$totalPages';
    }

    return AnnotatedRegion(
        value: getOverlayStyle(context),
        child: Scaffold(
            body: SafeArea(
          child: Stack(alignment: Alignment.topLeft, children: [
            ColorFiltered(
              colorFilter: ColorFilter.mode(Colors.white,
                  darkMode ? BlendMode.difference : BlendMode.dst),
              child:
                  _createPdfView(),
            ),
            if (showLeftPane) _createLeftMenu(),
            if (showMenu && !showLeftPane)
              SizedBox(
                height: 60,
                child: _createMenuWidget(),
              ),
            if (showMenu && !showLeftPane)
              Positioned(
                bottom: 0,
                left: 0,
                right: 0,
                child: Text('Read'),
              )
          ]),
        )));
  }
`

`Widget _createPdfView() {
    var panAxis = PanAxis.free;
    return PdfViewer.file(
      widget.pdfPath,
      // Set password provider to show password dialog
      passwordProvider: () => passwordDialog(context),
      controller: controller,
      params: PdfViewerParams(
        enableTextSelection: false,
        panAxis: panAxis,
        maxScale: 8,
        onViewSizeChanged: (viewSize, oldViewSize, controller) {
          if (oldViewSize != null) {
            //
            // Calculate the matrix to keep the center position during device
            // screen rotation
            //
            // The most important thing here is that the transformation matrix
            // is not changed on the view change.
            final centerPosition = controller.value.calcPosition(oldViewSize);
            final newMatrix = controller.calcMatrixFor(centerPosition);
            // Don't change the matrix in sync; the callback might be called
            // during widget-tree's build process.
            Future.delayed(
              const Duration(milliseconds: 200),
              () => controller.goTo(newMatrix),
            );
          }
        },
        viewerOverlayBuilder: (context, size, handleLinkTap) => [
          //
          // Example use of GestureDetector to handle custom gestures
          //
          GestureDetector(
            behavior: HitTestBehavior.translucent,
            // If you use GestureDetector on viewerOverlayBuilder, it breaks link-tap handling
            // and you should manually handle it using onTapUp callback
            onTapUp: (details) {
              if (!handleLinkTap(details.localPosition)) {
                setState(() {
                  if (showLeftPane) {
                    showLeftPane = false;
                  } else {
                    showMenu = !showMenu;
                  }
                });
              }
            },
            onDoubleTap: () {
              controller.zoomUp(loop: true);
            },
            // Make the GestureDetector covers all the viewer widget's area
            // but also make the event go through to the viewer.
            child: IgnorePointer(
              child: SizedBox(width: size.width, height: size.height),
            ),
          ),
          //
          // Scroll-thumbs example
          //
          // Show vertical scroll thumb on the right; it has page number on it
          PdfViewerScrollThumb(
            controller: controller,
            orientation: ScrollbarOrientation.right,
            thumbSize: const Size(30, 30),
            thumbBuilder: (context, thumbSize, pageNumber, controller) =>
                InkWell(
                    onTap: () async {
                      final page = await showDialog<int>(
                        context: context,
                        builder: (context) => PageInputDialog(
                          pageCount: controller.pageCount,
                        ),
                      );

                      if (page != null) {
                        await controller.goToPage(pageNumber: page);
                      }
                    },
                    child: Container(
                      alignment: Alignment.center,
                      decoration: const BoxDecoration(
                          image: DecorationImage(
                              image: AssetImage('assets/icon/page_number.png'),
                              fit: BoxFit.cover)),
                      child: Padding(
                          padding: const EdgeInsets.only(left: 5),
                          child: Text(
                            pageNumber.toString(),
                            style: const TextStyle(
                                color: Colors.black54, fontSize: 10),
                          )),
                    )),
          ),
          // Just a simple horizontal scroll thumb on the bottom
          PdfViewerScrollThumb(
            controller: controller,
            orientation: ScrollbarOrientation.bottom,
            thumbSize: const Size(18, 8),
            thumbBuilder: (context, thumbSize, pageNumber, controller) =>
                ClipRRect(
              borderRadius: BorderRadius.circular(4),
              child: Container(color: Colors.grey),
            ),
          ),
        ],
        //
        // Loading progress indicator example
        //
        loadingBannerBuilder: (context, bytesDownloaded, totalBytes) => Center(
          child: CircularProgressIndicator(
            value: totalBytes != null ? bytesDownloaded / totalBytes : null,
            backgroundColor: Colors.grey,
          ),
        ),
        //
        // Link handling example
        //
        linkHandlerParams: PdfLinkHandlerParams(
          onLinkTap: (link) {
            if (link.url != null) {
              navigateToUrl(link.url!);
            } else if (link.dest != null) {
              controller.goToDest(link.dest);
            }
          },
        ),
        pagePaintCallbacks: [
          textSearcher.pageTextMatchPaintCallback,
          _paintMarkers,
        ],
        onDocumentChanged: (document) async {
          if (document == null) {
            documentRef.value = null;
            outline.value = null;
            _textSelections = null;
            _markers.clear();
          }
        },
        onViewerReady: (document, controller) async {
          documentRef.value = controller.documentRef;
          outline.value = await document.loadOutline();
          if (mounted) {
            setState(() {
              totalPages = controller.pageCount;
            });
          }

          final page = pref?.getInt(_createCurrentPageKey());
          if (page != null && page > 1) {
            controller.goToPage(pageNumber: page);
          }
        },
        onPageChanged: (page) {
          if (page != null && page > 1) {
            pref?.setInt(_createCurrentPageKey(), page);
          }
        },
        onTextSelectionChange: (selections) {
          _textSelections = selections;
        },
      ),
    );
  }`

**Comment by hnvmeta** [comment]
Thank you for your help. I discovered the issue: the method `gotoPage()` does't work properly because the Keyboard resizes PDF View when users enter a page number to jump.
I fix this issue by using this code: `return Scaffold(
      resizeToAvoidBottomInset : false,
      body: YourWidgets(),
    );`
