### ISSUE TITLE
Full width initial view

### ISSUE THREAD

**Issue by Nashwaay** [espresso3389/pdfrx#279]
If I want my pdf to occupy full available width and have no negative space, how can I do that?

Current initial state:
![image](https://github.com/user-attachments/assets/ae336b0b-3956-439d-8a83-73bab5eb5bdc)

Required initial state (manually zoom in for screenshot)
![image](https://github.com/user-attachments/assets/2f54e0f8-7d91-477d-b7d2-b8ef70efdb48)

**Comment by espresso3389** [comment]
Not a simple way, but the following fragment does it (even though it requires page number):

```dart
onViewSizeChanged: (viewSize, oldViewSize, controller) {
  Future.delayed(
    const Duration(milliseconds: 200),
      () => controller.goTo(
        calcMatrixForPageWidth(pageNumber: 2, controller: controller),
      ),
  );
}

...

Matrix4? calcMatrixForPageWidth({required int pageNumber, required PdfViewerController controller}) {
  final page = controller.layout.pageLayouts[pageNumber - 1];
  final viewSize = controller.viewSize;
  final margin = controller.params.margin;
  final zoom = (viewSize.width - margin * 2) / page.width;
  final y = (viewSize.height / 2 - margin) / zoom;
  return controller.calcMatrixFor(page.topCenter.translate(0, y),
     zoom: zoom, viewSize: viewSize);
}
```

**Comment by espresso3389** [comment]
The fit algorithm want to know which page to fit because each page has it's page width.

Another approach is, make all the page width same; it is to change layoutPage logic; then, the fit-to-width don't care which page to fit.

**Comment by espresso3389** [comment]
1.0.98 introduces several helper functions to deal with the issue:

- PdfViewerController.calcFitZoomMatrices
- PdfViewerController.calcMatrixFitWidthForPage
- PdfViewerController.calcMatrixFitHeightForPage

The first one returns list of possible fit-to-width matrices that can be used with PdfViewerController.goTo method:

```dart
final result = controller.calcFitZoomMatrices();
if (result.isNotEmpty) controller.goTo(result.first.matrix);
```

The methods returns list of PdfPageFitInfo objects. Each has pageNumber, matrix, and visibleAreaRatio that indicates how much portion of the page is shown in the view. In general, if multiple pages are shown inside the view, it's difficult to choose one of the page to do fit-to-width. But if visibleAreaRatio is small, the page is not the candidate page to fit.

So anyway, on the result list, the first one is the one that has the largest visibleAreaRatio and it "may be" the suitable page to do fit-to-width.

**Comment by Nashwaay** [comment]
the first one works, many thanks for your consistent support
![image](https://github.com/user-attachments/assets/590494d0-0e37-4a76-879e-3212a1879d2c)

**Comment by bradintheusa** [comment]
Can someone explain this a bit better and can I use it when using `PdfViewer.data`?
