### ISSUE TITLE
add variable for default zoom initial

### ISSUE THREAD

**Issue by DexterZP** [espresso3389/pdfrx#28]
it would be nice to have a variable to set the initial zoom, currently it starts with zoom, but would rather not!

**Comment by espresso3389** [comment]
It's relatively easy to add such parameter, but how do you specify the zoom ratio in real app?

I mean, you may want to know the PDF's page size before specifying the zoom ratio. Should I provide some callback mechanism to calculate the initial zoom ratio?

```dart
PdfViewer.url(...., zoom: (page, viewSize, margin) => (viewSize.width - margin * 2) / page.width, ...),
```

**Comment by DexterZP** [comment]
> É relativamente fácil adicionar esse parâmetro, mas como especificar a taxa de zoom no aplicativo real?
> 
> Quero dizer, você pode querer saber o tamanho da página do PDF antes de especificar a taxa de zoom. Devo fornecer algum mecanismo de retorno de chamada para calcular a taxa de zoom inicial?
> 
> ```dart
> PdfViewer.url(...., zoom: (page, viewSize, margin) => (viewSize.width - margin * 2) / page.width, ...),
> ```

you know when you finish rendering a pdf, and in that, you could assign a variable for when you finish rendering, make a setZoom for that

**Comment by DexterZP** [comment]
PdfViewer.url(...., zoomInitial: 1.0)

after you finish rendering

setZoom(zoomInitial)

**Comment by DexterZP** [comment]
Fit the page to the view

**Comment by espresso3389** [comment]
Then, do you think values other than 1.0 mean something? I think they're completely useless. And that is the reason why there is no parameter for initial zoom so far.
