### ISSUE TITLE
libpdfium.so has a corrupt string table index - ignoring

### ISSUE THREAD

**Issue by venus0707** [espresso3389/pdfrx#280]
The software exits when the file is opened (PdfViewer.file)

Linux(Debain)
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (9 天前) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2

**Comment by espresso3389** [comment]
At least, pdfrx 1.0.98's example viewer on the following environment running correctly:

```
[✓] Flutter (Channel stable, 3.27.1, on Ubuntu 24.04.1 LTS 5.15.167.4-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.27.1 on channel stable at /home/kawasaki/work/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 17025dd882 (9 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
```

One possible issue on your side is libpdfium.so downloaded on your machine is just broken. Clean everything and try again.
