### ISSUE TITLE
Scrolling from mouse, not working in web mode, only on desktop

### ISSUE THREAD

**Issue by DexterZP** [espresso3389/pdfrx#31]

**Comment by DexterZP** [comment]
I tested your example mode, and it doesn’t work either

**Comment by espresso3389** [comment]
Sorry, please turn off text selection by `enableTextSelection: false`. It affects the scrolling.

**Comment by espresso3389** [comment]
Woops, there seems another issue with Web.
[0.4.9](https://pub.dev/packages/pdfrx/versions/0.4.9) fixes the issue anyway.
