### ISSUE TITLE
Error in build web assembly flutter channel master

### ISSUE THREAD

**Issue by DexterZP** [espresso3389/pdfrx#33]
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/pdfrx-0.4.10/lib/src/widgets/pdf_page_text_overlay.dart(95,7): error G76B49859: The non-abstract class '_PdfTextRenderBox' is missing implementations for these members

**Comment by espresso3389** [comment]
pdfrx does not support master channel so far.
Anyway, the error you mentioned does not contain the most important info; what members are missing?

I'm guessing on the master channel, RenderBox class may introduces some new methods and they're missing on the current pfxrx implementation...

**Comment by DexterZP** [comment]
Is it possible to create a beta for this?

**Comment by espresso3389** [comment]
I don't know.

Basically, if you are using master or beta, you'd better do anything by yourself.
Futhermore, you don't give me the info I requested on the previous messages.

My time is very limited and I'm not your supporter. Please do it yourself before create such issues.

**Comment by espresso3389** [comment]
Anyway, I've tested on Flutter master just now and it works without any error:

```
[✓] Flutter (Channel master, 3.18.0-2.0.pre, on Ubuntu 22.04.3 LTS 5.15.137.3-microsoft-standard-WSL2, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources
```

![image](https://github.com/espresso3389/pdfrx/assets/1311400/80da4cd8-1f0d-4e8a-8bbf-8b2cc20706a8)
