### ISSUE TITLE
Execution failed for task ':pdfrx:configureCMakeDebug[armeabi-v7a]'. > [CXX1405] error when building with cmake using C:\Users\miraj\AppData\Local\Pub\Cache\hosted\pub.dev\pdfrx-0.4.10\android\CMakeLists.txt: Build command failed

### ISSUE THREAD

**Issue by miraj98hossain** [espresso3389/pdfrx#34]
After using this package while I am build my Project It is showing build exception.
The error says 
  -- Check for working CXX compiler: C:/Users/miraj/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/miraj/AppData/Local/Pub/Cache/hosted/pub.dev/pdfrx-0.4.10/android/.cxx/Debug/2m4q6j72/armeabi-v7a/CMakeFiles/CMakeOutput.log".

  CMake Error at CMakeLists.txt:62 (file):
    file Failed to create link
    'C:/Users/miraj/AppData/Local/Pub/Cache/hosted/pub.dev/pdfrx-0.4.10/android/.lib/latest'
    because existing path cannot be removed: File exists
3

  CMake Warning (dev) at CMakeLists.txt:66 (set):
    Cannot set "pdfrx_bundled_libraries": current scope has no parent.
  This warning is for project developers.  Use -Wno-dev to suppress it.
3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by espresso3389** [comment]
Did you enable Windows' Developer mode (symlink feature)?

If you don't do so, please do the following:

- Enable Developer Mode
- Delete `C:/Users/miraj/AppData/Local/Pub/Cache/hosted/pub.dev/pdfrx-0.4.10/android/.lib/latest` directory
- Rebuild the app

**Comment by miraj98hossain** [comment]
Thank You so Much !! It Worked.

**Comment by espresso3389** [comment]
7fee79415cea62254f0fd1a4132fe6a3a79d2944 adds a symlink-creation-check.
