### ISSUE TITLE
PdfViewer.uri is broken on web for non relative paths

### ISSUE THREAD

**Issue by jezell** [espresso3389/pdfrx#37]
PdfViewer.uri doesn't work with absolute URLs because it throws out everything but the path:

```dart
 @override
  Future<PdfDocument> openUri(
    Uri uri, {
    String? password,
    PdfPasswordProvider? passwordProvider,
    PdfDownloadProgressCallback? progressCallback,
  }) =>
      openFile(
        uri.path,
        password: password,
        passwordProvider: passwordProvider,
      );

  static bool _isPasswordError(dynamic e) =>
      e.toString().startsWith('PasswordException:');
}
```

if your URI requires the host / scheme, etc. you can't view the document. We were loading PDFs with pdf_render via remote URLs before, but those don't work with Pdfrx because of this. 

Because of #36 we can't manually load the pdfs and pass them to the viewer with http.get either.

**Comment by espresso3389** [comment]
[0.4.15](https://pub.dev/packages/pdfrx/versions/0.4.15) is released which contains the fix.
