### ISSUE TITLE
Feature Request: Texture like widget

### ISSUE THREAD

**Issue by espresso3389** [espresso3389/pdfrx#41]
Discussed on #21

[pdf_render](https://github.com/espresso3389/flutter_pdf_render) has [page level widget](https://github.com/espresso3389/flutter_pdf_render?tab=readme-ov-file#multi-page-view-using-listviewbuilder) and we need such widget.

**Comment by espresso3389** [comment]
[0.4.23](https://pub.dev/packages/pdfrx/versions/0.4.23) introduces [PdfDocumentViewBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder-class.html) and [PdfPageView](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder-class.html).

@jezell
I think PdfPageView can be used like Texture widget but I'm not sure whether it's what you want or not...

Example code:
```dart
PdfDocumentViewBuilder.asset(
  'assets/sample.pdf',
  builder: (context, document) => ListView.builder(
    itemCount: document?.pages.length ?? 0,
    itemBuilder: (context, index) {
      return Container(
        margin: const EdgeInsets.all(8),
        height: 240,
        child: Column(
          children: [
            SizedBox(
              height: 220,
              child: PdfPageView(
                document: document,
                pageNumber: index + 1,
              ),
            ),
            Text('${index + 1}'),
          ],
        ),
      );
    },
  ),
),
```

**Comment by jezell** [comment]
@espresso3389 looks good, I'll give it a shot!
