### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sdegenaar** [espresso3389/pdfrx#47]
Hi, this looks like a great promising library. Does searching for text work?
Thanks!

**Comment by espresso3389** [comment]
Technically, it's yes. You can use you can get [PdfPageText](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageText-class.html) by [PdfPage. loadText](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPage/loadText.html) and search pattern on [PdfPageText](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageText/fullText.html).

There are also [PdfPageTextFragment](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageTextFragment-class.html) that contains the page text rectangle corresponding to the text.

 [PdfPageText.getFragmentIndexForTextIndex](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageText/getFragmentIndexForTextIndex.html) is just a helper function that identfies [PdfPageTextFragment](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPageTextFragment-class.html) corresponding the text index.

I'm still working on the default text searching UI on PdfViewer so far.

**Comment by sdegenaar** [comment]
Thank you! Hopefully this is in there soon as will be a great addition. :-)

**Comment by sdegenaar** [comment]
I see this is in the code now... Thank you!

**Comment by espresso3389** [comment]
[0.4.26](https://pub.dev/packages/pdfrx/versions/0.4.26) introduces PdfTextSearcher that helps you to implement search feature on your app. See [README.md](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#text-search) for the overall usage.
