### ISSUE TITLE
During Android build, CMake '3.18.1' was not found in SDK

### ISSUE THREAD

**Issue by spring321** [espresso3389/pdfrx#48]
Gradle task assembleAppRelease failed with exit code 1

[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.22.1' found in SDK did not satisfy requested version.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':pdfrx'.
> java.lang.NullPointerException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assemblePadRelease'...                      
Gradle task assemblePadRelease failed with exit code 1

flutter doctor --verbose
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.4 22F66 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at /Users/spring/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (5 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    
    Apple M2
    
    not be able to run

**Comment by espresso3389** [comment]
I'm not gradle professional but in build.gradle, there's an explicit CMake version config.
I'm not sure why it is there and what happens if I remove the version specification...

**Comment by espresso3389** [comment]
On [0.4.31](https://pub.dev/packages/pdfrx/versions/0.4.31), I removed the version spec. on build.gradle anyway.

**Comment by espresso3389** [comment]
[flutter/flutter #75600](https://github.com/flutter/flutter/issues/75600#issuecomment-775733034) seems very similar.

**Comment by espresso3389** [comment]
New flutter projects such as pdfrx's example already has the following gradle version. Not affected by the gradle issue anyway.

https://github.com/espresso3389/pdfrx/blob/7ee94db883de777dbaf55cf9ade7f786b115f68b/example/android/gradle/wrapper/gradle-wrapper.properties#L5
