### ISSUE TITLE
PdfViewer Uint8List

### ISSUE THREAD

**Issue by sdegenaar** [espresso3389/pdfrx#49]
Is it possible to display data (Uint8List) in PdfViewer without first saving to  temp file? Viewing directly from data (Uint8List) returned from a rest call. Thanks!

**Comment by espresso3389** [comment]
You can firstly create [PdfDocumentRefData](https://pub.dev/documentation/pdfrx/0.4.26/pdfrx/PdfDocumentRefData-class.html) then pass it to [PdfViewer.documentRef](https://pub.dev/documentation/pdfrx/0.4.26/pdfrx/PdfViewer/PdfViewer.documentRef.html) constructor:

```dart
final documentRef = PdfDocumentRefData(data);

...

PdfViewer.documentRef(documentRef, ...)
```

You had better create some StatefulWidget and keep the `documentRef` as its member variable.
