### ISSUE TITLE
Debug running error while building  Android project.

### ISSUE THREAD

**Issue by mlican** [espresso3389/pdfrx#5]
The error message is as follows:
```
../pdfrx-0.2.1/lib/src/pdfium/pdfium_interop.dart:59:56: Error: listener expects a static function as parameter. dart:ffi only supports calling static Dart functions from native code. Closures and tear-offs are not supported because they can capture context.
    _nativeCallable = _NativeFileReadCallable.listener(readNative);
                                                       ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

And a deprecated splash screen error while using Android Studio for a Flutter project. The error message is as follows:
```
A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
```
I followed the provided link (flutter.dev/go/android-splash-migration) to review the migration steps, but I'm still unsure about how to resolve this issue.
Flutter version：3.13.9

**Comment by espresso3389** [comment]
Mmm, I'm not sure actually, but it seems NativeCallable.listener requires Flutter 3.16.0/Dart 3.2 (latest stable) combination.
Please update your Flutter version.

**Comment by espresso3389** [comment]
[0.2.2](https://pub.dev/packages/pdfrx/versions/0.2.2) has a fix for the issue; it explicitly specify Flutter 3.16.0/Dart 3.2 on its pubspec.yaml now.

**Comment by espresso3389** [comment]
Oh, and for android-splash, it's not related to the plugin.

**Comment by mlican** [comment]
> Oh, and for android-splash, it's not related to the plugin.

Update version `0.2.2`, this problem no longer exists. Thank you so much.
