### ISSUE TITLE
Null check operator used on a null value when addListener to PdfViewerController

### ISSUE THREAD

**Issue by pckimlong** [espresso3389/pdfrx#50]
I believe that because the controller is not yet ready, as I see there is an isReady property. However, I am uncertain about how to get notify when the controller is ready. My goal is to obtain the total number of pages from given PDF file and update the UI

**Comment by espresso3389** [comment]
For your purpose, the most suitable solution is to use [PdfViewerParams.onDocumentChanged](https://pub.dev/documentation/pdfrx/0.4.26/pdfrx/PdfViewerParams/onDocumentChanged.html) that is fired on every document change.

```dart
PdfViewer.asset('assets/some.pdf',
  params: PdfViewerParams(
    onDocumentChanged: (document) async {
        
    },
  ));
```




https://github.com/espresso3389/pdfrx/blob/0e5c8881d8cd621dc34bf18f7e7b1a5bf39901ec/example/lib/main.dart#L238
