### ISSUE TITLE
Open pdf though URI

### ISSUE THREAD

**Issue by neeltechuser** [espresso3389/pdfrx#55]
I am trying to use this method to run my pdf; it is a link given by the API.

 PdfViewer.uri(
                  Uri.parse(
                      'https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf'),
                      
but its going through errors

<img width="1194" alt="Screenshot 2024-02-02 at 12 08 26 PM" src="https://github.com/espresso3389/pdfrx/assets/154509024/f65525b1-00f1-4b1b-815f-2339090ae0d8">
 like this

**Comment by espresso3389** [comment]
What platform are you running your app?
If you're on Flutter Web, downloading of web contents is restricted by CORS.

Anyway, do you give me more info. about your situation?

**Comment by neeltechuser** [comment]
Yes, that was the problem.
It was my fault.  I didn't read the documentation well.
if I run Flutter Web with this command,

 "flutter run -d chrome --web-browser-flag "--disable-web-security""

It is running.
but it doesn't have a future, like  open URL inside the pdf.
I mean, I am trying to tap the URL inside the pdf, but nothing is happening.
for your reference.

   PdfViewer.uri(
                  Uri.parse(
                      'https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf'),
                      
                      
<img width="773" alt="Screenshot 2024-02-02 at 12 50 51 PM" src="https://github.com/espresso3389/pdfrx/assets/154509024/4151ab7e-4bb8-4666-a715-899eb03681d6">

**Comment by espresso3389** [comment]
Link handling is not enabled by default.
See [README.md](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#pdf-link-handling)'s instruction to enable it.
