### ISSUE TITLE
Null in _calcMatrixForArea when called from onDocumentChanged

### ISSUE THREAD

**Issue by mweller83** [espresso3389/pdfrx#56]
Hi!

Thanks for this library -- it's most definitely the best pdf viewer widget that's available!

I'm using it to write an application that allows users to select different PDFs and as soon as one PDF is loaded a search should start, so I have something like this:
```
Scaffold(...,
body: _currentPdf == null
          ? Container()
          : PdfViewer.file(
              _currentPdf!,
              controller: _pdfViewerController,
              params: PdfViewerParams(
                pagePaintCallbacks: [textSearcher.pageTextMatchPaintCallback],
                onDocumentChanged: (document) {
                  if (document != null) {
                     if (_pdfViewerController.isReady) {
                       textSearcher.startTextSearch(_currentHighlight!, caseInsensitive: true);
                       _pdfViewerController.goToPage(pageNumber: _currentPage!);
                    }
                  }
                },
              ),
            ),
 );
```
But then I get this error: 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _PdfViewerState._calcMatrixForArea (package:pdfrx/src/widgets/pdf_viewer.dart:911:31)
#1      _PdfViewerState._calcMatrixForPage (package:pdfrx/src/widgets/pdf_viewer.dart:958:7)
#2      _PdfViewerState._goToPage (package:pdfrx/src/widgets/pdf_viewer.dart:1134:9)
#3      PdfViewerController.goToPage (package:pdfrx/src/widgets/pdf_viewer.dart:1350:14)
#4      ExampleExpandableFabState.highlightText (package:pdfbox_example/main.dart:102:28)
#5      ExampleExpandableFabState.build.<anonymous closure> (package:pdfbox_example/main.dart:141:21)
#6      _PdfViewerState._notifyOnDocumentChanged.<anonymous closure> (package:pdfrx/src/widgets/pdf_viewer.dart:276:63)
#7      new Future.microtask.<anonymous closure> (dart:async/future.dart:280:37)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
So the PDF is not really "loaded" when `onDocumentChanged` is called it seems. Is there another callback I can use?

**Comment by espresso3389** [comment]
Oh, I see.
It seems that the document is ready but internal layout calculation is not finished at the moment.

**Comment by espresso3389** [comment]
[0.4.32](https://pub.dev/packages/pdfrx/versions/0.4.32) introduces [PdfViewerParams.onViewerReady](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/onViewerReady.html) that is called when the viewer gets ready.

Please take a look at the function.

**Comment by mweller83** [comment]
Thanks a lot! It doesn't dump anymore, but there's still something wrong:
When calling `_pdfViewerController.goToPage` for a short moment it goes to the correct page, then scrolls back to the first page. I can setup a minimal example if you want.

**Comment by espresso3389** [comment]
Is it impossible to pass `_currentPage` to [PdfViewer.file](https://pub.dev/documentation/pdfrx/0.4.33/pdfrx/PdfViewer/PdfViewer.file.html)'s `initialPageNumber` parameter?

Or

**Comment by espresso3389** [comment]
Or [PdfViewerParams.calculateInitialPageNumber](https://pub.dev/documentation/pdfrx/0.4.33/pdfrx/PdfViewerParams/calculateInitialPageNumber.html) is a good place to do your all task. The function is called before navigating to the initial page (because it calculagte the initial page) but it is called after almost all initialization is finished.

**Comment by espresso3389** [comment]
Oh, another possibility is that  `goToFirstMatch` parameter of [PdfTextSearcher.startTextSearch](https://pub.dev/documentation/pdfrx/0.4.33/pdfrx/PdfTextSearcher/startTextSearch.html) may affect the behavior. If so, please turn it off.

**Comment by mweller83** [comment]
> Oh, another possibility is that `goToFirstMatch` parameter of [PdfTextSearcher.startTextSearch](https://pub.dev/documentation/pdfrx/0.4.33/pdfrx/PdfTextSearcher/startTextSearch.html) may affect the behavior. If so, please turn it off.

Thank you! I just needed to change this parameter. Now everything is working as expected. :-)
