### ISSUE TITLE
conflict with audioplayers: ^5.2.1

### ISSUE THREAD

**Issue by lin1270** [espresso3389/pdfrx#60]
conflict with audioplayers: ^5.2.1

Because pdfrx >=0.4.11 depends on js ^0.7.0 and audioplayers_web >=2.1.0 depends on js
  ^0.6.4, pdfrx >=0.4.11 is incompatible with audioplayers_web >=2.1.0.
And because audioplayers >=5.2.0 depends on audioplayers_web ^4.1.0, pdfrx >=0.4.11 is
  incompatible with audioplayers >=5.2.0.
So, because jingyuan depends on both audioplayers ^5.2.1 and pdfrx 0.4.36, version
  solving failed.

**Comment by espresso3389** [comment]
Such kind of dependency conflicts cannot be fixed easily. If changing some, it breaks another.
So, it should be fixed on app side. You can use [dependency_overrides](https://dart.dev/tools/pub/dependencies).

**Comment by lin1270** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
