### ISSUE TITLE
CMake version incompatibility issue introduced on 0.4.31

### ISSUE THREAD

**Issue by Zhanerkeb** [espresso3389/pdfrx#62]
App requires 3.18.1 or higher CMake version, however still depends on 3.10.2.4988404 version. How to resolve?

Execution failed for task ':pdfrx:configureCMakeDebug'.
/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake": error=2, No such file or directory

**Comment by Zhanerkeb** [comment]
If I install 3.10.2, it gives me this error:
.pub-cache/hosted/pub.dev/pdfrx-0.4.36/android/CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.18.1 or higher is required.  You are running version 3.10.2

**Comment by espresso3389** [comment]
In normal situation, you don't have to install cmake manually. `flutter build` or `flutter run` automatically installs them.
Did you run `flutter clean` before running build?

**Comment by Zhanerkeb** [comment]
yes

**Comment by espresso3389** [comment]
If so, please delete `build/` directory completely and try again.

**Comment by espresso3389** [comment]
Ah, you also need to remove '.pub-cache/hosted/pub.dev/pdfrx-0.4.36/android/.cxx' if you encounter something.
Try to remove '.pub-cache/hosted/pub.dev/pdfrx-0.4.36' or '.pub-cache/' completely may fix the issue.

**Comment by Zhanerkeb** [comment]
> Ah, you also need to remove '.pub-cache/hosted/pub.dev/pdfrx-0.4.36/android/.cxx' if you encounter something. Try to remove '.pub-cache/hosted/pub.dev/pdfrx-0.4.36' or '.pub-cache/' completely may fix the issue.

Didn't help(

**Comment by Zhanerkeb** [comment]
0.4.30 version builds, from 31 the error occurs

**Comment by espresso3389** [comment]
Yes, I know that. [The change on 0.4.31](https://github.com/espresso3389/pdfrx/issues/48#issuecomment-1923528789) is deeply related to the issue.
But on a clean build envrionment, it does not affect anything and build runs successfully. So some of the garbages on your environment may actually affect the issue...

**Comment by espresso3389** [comment]
If I revert the change, it breaks another one's build environment. And I don't think it's better to specify such CMake version explicitly on build.gradle anyway. CMakeFile.txt specifies it's own CMake requirement version and normally, build process automatically chooses/downloads proper CMake version automatically "in theory".

**Comment by espresso3389** [comment]
Oh, how did you install CMake manually? From Android Studio's SDK manager? or any other method?

**Comment by espresso3389** [comment]
If you've installd CMake not from SDK manager, please firstly uninstall it. And clean all the related directories and do `flutter clean`, and rerty build.

**Comment by Zhanerkeb** [comment]
> Oh, how did you install CMake manually? From Android Studio's SDK manager? or any other method?

yes, from SDK manager

**Comment by Zhanerkeb** [comment]
<img width="653" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/5b7f757b-97b8-4286-acf9-b4a25b83a921">

**Comment by Zhanerkeb** [comment]
<img width="694" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/dd62e479-31c5-4eca-a1a8-d1f4ea73627c">

**Comment by espresso3389** [comment]
[0.4.37](https://pub.dev/packages/pdfrx/versions/0.4.37) contains the fix explained above:

https://github.com/espresso3389/pdfrx/blob/755e65ff3c19d776619f73060dca6728d60d7fb5/android/build.gradle#L42-L48

Please try the latest version.
