### ISSUE TITLE
Scrolling fast on PdfViewer causes a bounce back in the end of document

### ISSUE THREAD

**Issue by AdityaHighspot** [espresso3389/pdfrx#64]
Hi, I'm unable to record my screen currently, but I notice a weird behaviour on real devices. If I scroll fast and reach the end of document, it flings/ bounces back up. So I can only scroll slowly and use the pdf viewer. It's more evident on PDF files that have landscape pages instead of portrait ones.

Could you please look into this? I think there can be a flag in PdfViewerParams to disable this animation/effect?

**Comment by espresso3389** [comment]
Duplicate of #61
