### ISSUE TITLE
is it possible to save and restore text selections?

### ISSUE THREAD

**Issue by MarcVanDaele90** [espresso3389/pdfrx#65]
I would like to be able to
- select text (in a specific color) and keep the colored text visible in the pdf
- select some more text (in another color) and also keep this second part visible

Additionally, I would like to be able to save these selections and be able to restore them when I open the document a second time. 
I don't need to store them in the pdf itself since different users can create different annotations.

Is this technically feasible? If so, do you plan to tackle this somewhere in the future?

**Comment by espresso3389** [comment]
Basically, you can overlay anything on PDF pages using either [PdfViewerParams.pagePaintCallbacks](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pagePaintCallbacks.html) or [PdfViewerParams.viewerOverlayBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/viewerOverlayBuilder.html).

The first one is using Canvas and it is faster if you want to overlay many things.
The second one is useful if you want to place widgets over the page.

And, then, `PdfTextSearcher.pageTextMatchPaintCallback` is a good example to use `PdfViewerParams.pagePaintCallbacks`:

https://github.com/espresso3389/pdfrx/blob/927999498cb3486ce62be8beacb8ca150aa3260f/lib/src/widgets/pdf_text_searcher.dart#L254-L275

There are two important things here:
- Search result is in [PdfTextMatch](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfTextMatch-class.html) and it has a very useful method named [PdfTextMatch.fromTextRange](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfTextMatch/fromTextRange.html), which converts text index/end combination to [PdfRect](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfRect-class.html)
- [PdfRect](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfRect-class.html) can be easily converted to in-canvas coordinate system

Text selection is not text-match but `PdfTextMatch` can be reused for highlighting text selections.

Only the missing piece here is to get current text selection from `PdfViewer`. I'll implement it.

**Comment by MarcVanDaele90** [comment]
This looks very promising! Thanks!

**Comment by espresso3389** [comment]
On 76b34c096075970f3d31a640d25f664d35d950ac, I've introduced `PdfViewerParams.onTextSelectionChange`.

```dart
// save the last text selection
PdfTextRanges? _selectedText;

PdfViewer.asset('some',
  params: PdfViewerParams(
    pagePaintCallbacks: [
      // example to draw the saved text selection
      _paintSelection,
    ],
    onTextSelectionChange: (selection) {
      // just an example; keep the last text selection
      if (selection != null && selection.isNotEmpty) {
        _selectedText = selection;
      }
     // hopefully, the widget is automatically setState
    },
  ]),
...

// simple example to paint the last selected ranges
void _paintSelection(Canvas canvas, Rect pageRect, PdfPage page) {
  if (_selectedText == null ||
      _selectedText!.pageText.pageNumber != page.pageNumber) {
    return;
  }
  final paint = Paint()
    ..color = Colors.green.withOpacity(0.5)
    ..style = PaintingStyle.fill;
  for (final range in _selectedText!.ranges) {
    final f = PdfTextRangeWithFragments.fromTextRange(
        _selectedText!.pageText, range.start, range.end);
    if (f != null) {
      canvas.drawRect(
          f.bounds.toRectInPageRect(page: page, pageRect: pageRect), paint);
    }
  }
}
```

**Comment by espresso3389** [comment]
[0.4.40](https://pub.dev/packages/pdfrx/versions/0.4.40) is released!

**Comment by espresso3389** [comment]
75aa49f576b6df3f6ea17a93d7c1c9e9e7e1c2eb updated the example to have markers pane. The main logic is there;

https://github.com/espresso3389/pdfrx/blob/75aa49f576b6df3f6ea17a93d7c1c9e9e7e1c2eb/example/lib/main.dart#L310-L312

https://github.com/espresso3389/pdfrx/blob/75aa49f576b6df3f6ea17a93d7c1c9e9e7e1c2eb/example/lib/main.dart#L323-L347

On the example UI, you can see three color buttons on the toolbar. After selecting some text and tap one of them, you can add marker:

https://github.com/espresso3389/pdfrx/assets/1311400/72ab9047-d5b1-42f9-b13d-ec0195bf591c
