### ISSUE TITLE
Night mode (Dark mode) support ?

### ISSUE THREAD

**Issue by kisrar** [espresso3389/pdfrx#68]
Hi @espresso3389 , thanks for this awesome plugin.

Do you have any plans to add the night mode support?

**Comment by espresso3389** [comment]
What do you expect by "night mode support"?

PDF files are typically in white background; colors on PDF document typically assumes white background.
How do I handle such colors?

**Comment by kisrar** [comment]
Right now, I am using two plugins in my app for PDF.
1. pdfrx: as it is supports search feature
2. https://pub.dev/packages/flutter_pdfview : As it has night mode.

I do not know, how `flutter_pdfview ` plugin is handling the colors for night mode, but I am sure it is doable.

**Comment by espresso3389** [comment]
Do you give me any kind of screenshot or something that visually explains what night mode stands for?

**Comment by kisrar** [comment]
# 1. PDF preview using `pdfrx` plugin:
![image](https://github.com/espresso3389/pdfrx/assets/112469871/9493eccf-827f-470a-83a2-00877d218fae)

# 2. PDF preview using `flutter_pdfview` plugin (in night mode):
![image](https://github.com/espresso3389/pdfrx/assets/112469871/b6415b1e-4cd9-48e4-b836-2ec0f18fbe33)

**Comment by espresso3389** [comment]
Another person just introduced a way to invert the viewer content easily:

https://github.com/espresso3389/pdfrx/issues/46#issuecomment-1909476596

```dart
class _ExampleState extends State<Example> {
  final controller = PdfViewerController();
  bool darkMode = false;

  @override
  Widget build(BuildContext context) {
    final pdfWidget = ColorFiltered(
      colorFilter: ColorFilter.mode(
          Colors.white, darkMode ? BlendMode.difference : BlendMode.dst),
      child: PdfViewer.file(widget.path, controller: controller),
    );

    return Scaffold(
      appBar: AppBar(
        title: const Text('TEST'),
        actions: [
          IconButton(
            onPressed: () => setState(() => darkMode = !darkMode),
            icon: const Icon(Icons.dark_mode),
          ),
        ],
      ),
      body: pdfWidget,
    );
  }
}
```

**Comment by espresso3389** [comment]
I'm not sure whether should I introduce it as a standard feature or not. But apparently, it's so easy to implement that.

**Comment by kisrar** [comment]
Hi @espresso3389  Thanks a lot, above code snippet worked and I am getting the desired output. 
Although night mode support seems to be quite easy to implement, but that can be considered as a `feature` and you can document this feature in the readme file as well.

You can add a bool parameter in `PdfViewerParams` constructor for night mode feature. By default it should be false, but if developer passes true for `nightMode`, then it should work based on the above code snippet.

Once again thanks a lot, now I do not need to depend on other plugins for pdf night mode 😃

**Comment by espresso3389** [comment]
On 1227b0fad8a07850802d412426b48c2d6f1cb05b, I've added note about [dark/night mode support](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#darknight-mode-support) on README.md.
