### ISSUE TITLE
Zoom in/out bug with PDF in landscape 

### ISSUE THREAD

**Issue by chriswg3** [espresso3389/pdfrx#69]
When i display a PDF in landscape the InteractiveViewer does not allow to zoom to the minimum. 
I think this is becaus the bounderyMargin setting of the InteractiveViewer. 

if I set it to:

` iv.InteractiveViewer(
                      transformationController: _txController,
                      constrained: false,
                      boundaryMargin: const EdgeInsets.all(double.infinity),`

the zoom in / out works like it should.

Would be fine to have an option to set this parameter from outside.

**Comment by espresso3389** [comment]
Could you explain me more about your problem?

I think the behavior is fine even with single page landscale PDF:

![image](https://github.com/espresso3389/pdfrx/assets/1311400/4100a372-83c8-4d0d-92a1-88f35399bf95)

**Comment by chriswg3** [comment]
You can see the problem if you try it on android and zoom in and out...

**Comment by espresso3389** [comment]
Could you explain more? I'm not sure what's your problem.

**Comment by espresso3389** [comment]
Actually, I've found an issue on PdfPageAnchor behavior and fixed it. But it has nothing to do with bounderyMargin:

https://github.com/espresso3389/pdfrx/blob/bae7c2f5205b591d0b7206aa6d8e9ffdf0ca98c3/lib/src/widgets/pdf_viewer.dart#L939-L982

**Comment by chriswg3** [comment]
https://github.com/espresso3389/pdfrx/assets/120425754/c3745f77-8b55-4fe1-a902-77bd2c6123df

**Comment by espresso3389** [comment]
Oh, I see.

**Comment by espresso3389** [comment]
[0.4.44](https://pub.dev/packages/pdfrx/versions/0.4.44) fixes the issue; PdfViewerParams.boundaryMargin is working again and the new default is `EdgeInsets.all(double.infinity)`.

By the way, I could not remember why I've removed `boundaryMargin` parameter from the code.

**Comment by chriswg3** [comment]
You are using the parameter on several other places, are you sure that everything is ok then? Maybe you removed the parameter because of another bug?

**Comment by espresso3389** [comment]
I think boundaryMargin should be there anyway. I had been just dropped mistakenly in some recent version.
