### ISSUE TITLE
Rendered text is soft

### ISSUE THREAD

**Issue by chantheepic** [espresso3389/pdfrx#7]
Windows (Left is rendered on Edge, Right is on Flutter Windows debug screen)
![aliasing](https://github.com/espresso3389/pdfrx/assets/33669637/a9a4a528-febb-43be-84b4-311d7f29a033)

Web (Left is rendered on Edge, Right is on Flutter Web on Edge)
![aliasing2](https://github.com/espresso3389/pdfrx/assets/33669637/86947b06-636a-4ade-833c-55cfb3cd4478)

It's not as noticeable on Flutter Windows, but in both cases, Flutter seems to have softer text. I'm wondering if this is caused by render options PDFium and pdf.js or if Flutter is applying some anti-aliasing on the component. Any pointers for sharpening up the text would be helpful.

**Comment by espresso3389** [comment]
Mmm, the line edges are blurred too much. Is this a real vector PDF? Or JPEG compressed image PDF?

**Comment by chantheepic** [comment]
I believe it is a proper vector PDF. I've uploaded the document below.

[hello2.pdf](https://github.com/espresso3389/pdfrx/files/13710160/hello2.pdf)

**Comment by espresso3389** [comment]
I see your point. Flutter Web version seems a little softer; not solid.

<img width="499" alt="edge_fweb" src="https://github.com/espresso3389/pdfrx/assets/1311400/efd19e5b-d364-44cc-b321-c40f881e039d">

**Comment by chantheepic** [comment]
Yes, Flutter Web is definitely softer.
But this is also visible when viewing on Windows (Flutter Windows Application).
![image](https://github.com/espresso3389/pdfrx/assets/33669637/2e999455-bea1-43e5-9918-3d631ae4d094)
The right side shows the Windows application debug screen. You can tell that F in the phrase "Filing Status" is softer on the right.

I can't tell if this is an issue with the way Flutter is rendering the view or if it's an issue inherent in PDFium and pdf.js.

**Comment by espresso3389** [comment]
I found that even the Windows version is softer than the rendering result on Google Chrome's PDF Viewer though both are built on same pdfium...

**Comment by espresso3389** [comment]
The actual cause of the issue is apparently Flutter's system. InteractiveViewer do fractional scaling and image pixels do not snapped on the actual display's pixel grids.

Flutter issues like [#90926](https://github.com/flutter/flutter/issues/90926) is actually related to this but, anyway, InteractiveViewer could not be better in such way :(

**Comment by chantheepic** [comment]
Is that also why the rendered PDF for Flutter Web has soft text?
Since Flutter Web is using PDF.js, I thought it might be possible to render at double scale or double viewport size and then downscaling fit the screen.

**Comment by espresso3389** [comment]
For mobile devices and high-dpi devices, pdfrx does high-resolution rendering for pages.
But if your machine is low-resolution configed, it does not do anything for rendering.

So, anyway, [0.3.0](https://pub.dev/packages/pdfrx/versions/0.3.0) introduces [PdfViewerParams.devicePixelRatioOverride](https://github.com/espresso3389/pdfrx/blob/master/lib/src/pdfrx_widgets.dart#L1318) to override the rendering resolution.

Set 2.0 or more to the value will generate better quality though normally it uses the value from [MediaQuery.of(context).devicePixelRatio](https://api.flutter.dev/flutter/widgets/MediaQueryData/devicePixelRatio.html).

And, basically it will take more memory if you use higher value to it, but pdfrx normally keeps only 3 pages on memory and it does not cost so much in reality.

**Comment by espresso3389** [comment]
If you set `devicePixelRatioOverride: 3`, the overall sharpness seems comparable to Chrome's PDF viewer though there're still several rendering differences like constrast and edge smoothness.

**Comment by chantheepic** [comment]
It appears that `devicePixelRatioOverride: 2` is perfect for my case.
Thank you for the quick triage and update!

**Comment by thomas4Bitcraft** [comment]
Is this not possible anymore? I run the app in the web in a container at the moment and it looks like this: 
![image](https://github.com/espresso3389/pdfrx/assets/44415527/70e65b74-b1d3-47d2-aa9d-4cbe01a1e6f9)

**Comment by espresso3389** [comment]
@thomas4Bitcraft
[PdfViewerParams.getPageRenderingScale](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/getPageRenderingScale.html) replaces `devicePixelRatioOverride`.
