### ISSUE TITLE
CMake causing build failures on Android runs

### ISSUE THREAD

**Issue by ClaireDavis** [espresso3389/pdfrx#70]
I'm attempting to run an android build after integrating `pdfrx v 0.4.42` and getting the following build failure related to CMake.  I saw [this previous issue](https://github.com/espresso3389/pdfrx/issues/62) related to CMake, but this appears to be different.

This is the build failure I'm seeing:

```
What went wrong:
Execution failed for task ':pdfrx:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /home/circleci/.pub-cache/hosted/pub.dev/pdfrx-0.4.42/android/CMakeLists.txt: Build command failed.
  Error while executing process /usr/bin/cmake with arguments {-H/home/circleci/.pub-cache/hosted/pub.dev/pdfrx-0.4.42/android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=19 -DANDROID_PLATFORM=android-19 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/opt/android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/opt/android/sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/opt/android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/circleci/project/flutter/app/build/pdfrx/intermediates/cxx/Debug/491z64x2/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/circleci/project/flutter/app/build/pdfrx/intermediates/cxx/Debug/491z64x2/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/home/circleci/.pub-cache/hosted/pub.dev/pdfrx-0.4.42/android/.cxx/Debug/491z64x2/arm64-v8a -GNinja}
  -- Configuring incomplete, errors occurred!
  See also "/home/circleci/.pub-cache/hosted/pub.dev/pdfrx-0.4.42/android/.cxx/Debug/491z64x2/arm64-v8a/CMakeFiles/CMakeOutput.log".

  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

Output of CMakeOutput.log:
```
The target system is: Android - 1 - aarch64
The host system is: Linux - 5.19.0-1027-gcp - x86_64
```

Do you have any idea what might be going wrong here?

Thanks for your help!

<details>
  <summary>Flutter Doctor</summary>
  [✓] Flutter (Channel beta, 3.19.0-0.3.pre, on macOS 14.3 23D56 darwin-arm64, locale en-US)
    • Flutter version 3.19.0-0.3.pre on channel beta at /Users/clairedavis/fvm/versions/3.19.0-0.3.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1b197762c5 (2 weeks ago), 2024-01-25 22:23:26 -0800
    • Engine revision 968e2945c7
    • Dart version 3.3.0 (build 3.3.0-279.2.beta)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/clairedavis/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/clairedavis/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.
</details>

**Comment by espresso3389** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Ninja".

Apparently, `ninja` command is missing. Normally it is installed during the build process.

On my environment (macOS), it seems ninja is placed at `~/Library/Android/sdk/cmake/3.18.1/bin/ninja`

Could you check whether it exists or not?

**Comment by ClaireDavis** [comment]
I'm using a linux machine for this build in ci.  I _think_ the problem might be that the default generator on linux is the `Unix Makefiles, not Ninja.

The error is saying "`CMAKE_MAKE_PROGRAM` is not set" which makes me think that you may need to do what it says at the bottom of [this android documentation](https://developer.android.com/studio/projects/configure-cmake) and set the `CMAKE_MAKE_PROGRAM`?

**Comment by espresso3389** [comment]
I don't know about `CMAKE_MAKE_PROGRAM` but I've just checked the build on a docker container:

```
docker run -it --rm ghcr.io/cirruslabs/flutter
```

```
git clone https://github.com/espresso3389/pdfrx
cd pdfrx/example/
flutter build appbundle --release --verbose
```

And it finished correctly.

And, in the build log, I found the following lines:

```
Starting process 'command '/opt/android-sdk-linux/cmake/3.18.1/bin/cmake''. Working directory: /pdfrx/android
Command: /opt/android-sdk-linux/cmake/3.18.1/bin/cmake -H/pdfrx/android -DCMAKE_SYSTEM_NAME=Android
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=19 -DANDROID_PLATFORM=android-19 -DANDROID_ABI=arm64-v8a
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/opt/android-sdk-linux/ndk/23.1.7779620
-DCMAKE_ANDROID_NDK=/opt/android-sdk-linux/ndk/23.1.7779620
-DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk/23.1.7779620/build/cmake/android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=/opt/android-sdk-linux/cmake/3.18.1/bin/ninja
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/pdfrx/example/build/pdfrx/intermediates/cxx/RelWithDebInfo/6y5v2333/obj/arm64-v8a
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/pdfrx/example/build/pdfrx/intermediates/cxx/RelWithDebInfo/6y5v2333/obj/arm64-v8a
-DCMAKE_BUILD_TYPE=RelWithDebInfo -B/pdfrx/android/.cxx/RelWithDebInfo/6y5v2333/arm64-v8a -GNinja
```

The differences from your one are:

- NDK version
  - 23.1.7779620 vs. 21.4.7075529
- `CMAKE_MAKE_PROGRAM`
  - `/opt/android-sdk-linux/cmake/3.18.1/bin/ninja`
- `CMAKE_BUILD_TYPE`
  - `RelWithDebInfo` vs. `Debug` (But it's not the problem I guess)
- `-GNinja`

**Comment by espresso3389** [comment]
The most important difference is absence of `-GNinja` and `CMAKE_MAKE_PROGRAM` may be implied by `-GNinja` I guess.

The question here is; who is setting (or removing) `-GNinja` on your build env.

**Comment by espresso3389** [comment]
Any more details?

**Comment by btrautmann** [comment]
Note for those that may find this in the future:

As @espresso3389 points out above, things should work fine if using the Flutter docker image from cirruslabs. In some cases on an _android_ image, however, `ninja` won't be pre-installed and you'll get the error mentioned in OP.

Adding the below to our `config.yml` resolved this:

```yaml
- run:
    name: Install Ninja
    command: |
      sudo apt-get update
      sudo apt-get install ninja-build
      echo 'export CMAKE_MAKE_PROGRAM=/usr/bin/ninja' >> $BASH_ENV
```
