### ISSUE TITLE
On Android version 5.1.1, plugin not working

### ISSUE THREAD

**Issue by kisrar** [espresso3389/pdfrx#72]
## Screenshot that I received from my Production App user:
![Screenshot_2024-02-11-10-55-07-43](https://github.com/espresso3389/pdfrx/assets/112469871/e552c26e-bce4-4069-a7f1-f5c90d15068b)

**Comment by espresso3389** [comment]
Basically I have no idea what Android versions actually supported.

pdfrx depends on [bblanchon/pdfium-binaries](https://github.dev/bblanchon/pdfium-binaries) and searching the source code shows me it uses:

https://github.com/bblanchon/pdfium-binaries/blob/c05ee82d7afe7b5b067dbe01befcc9e6eef83ede/steps/08-test.sh#L12-L26

```
case "$OS" in
  android)
    case "$CPU" in
      arm)
        PREFIX="armv7a-linux-androideabi19-"
        ;;
      arm64)
        PREFIX="aarch64-linux-android21-"
        ;;
      x64)
        PREFIX="x86_64-linux-android21-"
        ;;
      x86)
        PREFIX="i686-linux-android19-"
        ;;
```

https://github.com/bblanchon/pdfium-binaries/blob/c05ee82d7afe7b5b067dbe01befcc9e6eef83ede/steps/01-install.sh#L24

- `ANDROID_NDK_VERSION="r25c"`

And, according to [NDK r25c releasenote](https://github.com/android/ndk/wiki/Changelog-r25#r25c), it still supports APIs 19 and 20. (It seems SDK r26 removes the support).

So, 

- for arm/x86 binaries, it supports 19+
- for arm64/x64, it supports 21+

pdfrx does not specify any explicit NDK version and `minSdkVersion` is set to 19.

And Android 5.1.1 is 22. Is is really a Android version error??

Anyway, the screen explains that the library is correctly loaded but FPDF_InitLibraryWithConfig is not found.
I could not determine whether it is a Android version error or not.

By the way, the error screen can be replaced if you implement [PdfViewerParams.errorBannerBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/errorBannerBuilder.html).

**Comment by kisrar** [comment]
Hi @espresso3389, as now  I am only using the `pdfrx` plugin, so many of my production users reported this issue.
In order to verify the `pdfrx` plugin behaviour, I created an emulator with API level 22 (Android 5.1). It seems the `pdfrx` plugin is not working on that version (attaching the screenshot of the emulator for your reference).
![image](https://github.com/espresso3389/pdfrx/assets/112469871/196685aa-7c5b-4d56-9ff4-2c70dd1f9a6c)

Let me know if the solution is feasible, else I will have to use `pdfrx` with old pdf plugins as well to support the Android 5.1+ devices.

**Comment by espresso3389** [comment]
I found a post: 
https://github.com/bblanchon/pdfium-binaries/issues/147#issuecomment-1837427189

> Chromium dropped support for Android API 23 a year ago:
> https://groups.google.com/a/chromium.org/g/chromium-dev/c/z_RvoPoIeoM

So the final answer is; pdfrx runs on API 24+ or later.

**Comment by espresso3389** [comment]
According to several statistics, Android 5/6 share is smaller than 3%.

It's not worth supporting them.

**Comment by espresso3389** [comment]
Because the deprecation starts on Oct 2022, the releases before  [pdfium-binaries 5323](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium/5323) may be frx the issue.

So creating a fork that changes the release version to them may work.

**Comment by espresso3389** [comment]
I've tested [PDFium 106.0.5215.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F5215) with

patching `pdfrx/android/CMakeLists.txt` with the following diff:

```
# PDFium 106.0.5215.0
# Aug 3, 2022
# https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F5215
set(PDFIUM_RELEASE chromium%2F5215)
```

and run it on API 22 simulator. And the result is same. It does not find `FPDF_InitLibraryConfig`...

**Comment by espresso3389** [comment]
Interesting things here is that FPDF_InitLibrary, FPDF_GetPageCount, FPDF_GetDocPermissions can be called correctly.
So, if I replaces call to FPDF_InitLibraryConfig with FPDF_InitLibrary, the next exception occurred when calls FPDF_GetSecurityHandlerRevision.

Apparently functions such as FPDF_InitLibrary and FPDF_GetSecurityHandlerRevision calls some Android API functions that is not supported on API 22.

I didn't have time to investigate the issue further. So anyway, currently I cannot support Android API 22.

**Comment by kisrar** [comment]
Thanks a lot @espresso3389  for the `pdfrx` plugin. 
So, to support the old devices as well, I am using the `pdfrx` in conjunction with `pdf_render` plugin. 
For now, it is OK, but ultimately I will find a solution to use only a single plugin (as using 2 plugins increased the app size as well).
