### ISSUE TITLE
Not search specific letter

### ISSUE THREAD

**Issue by Prafu-94** [espresso3389/pdfrx#73]
Here when search using "PdfTextSearcher.startTextSearch" it will search overall word and highlight word but i want to highlight only single letter

**Comment by espresso3389** [comment]
At least currently, Web version could not do character level selection. pdf.js sample actually does it but the pdf.js API does not provide any APIs to do that; it seems it uses SVG or such to do that.

**Comment by espresso3389** [comment]
The issue has been discussed on #4 but should we need a separate issue?

**Comment by Prafu-94** [comment]
No
