### ISSUE TITLE
too many projects still depend on js ^0.6.3

### ISSUE THREAD

**Issue by Yoda-Man** [espresso3389/pdfrx#78]
And because firebase_core_web >=1.0.0 depends on js ^0.6.3 and pdfrx >=0.4.11 depends on js ^0.7.0, pdfrx >=0.4.11 is incompatible with
  firebase_core.

it could take months for guys to upgrade to js 0.7.0

**Comment by espresso3389** [comment]
It seems that 0.4.11 (6c98abc77aa6e3daa131e86d4f90cb0854b78b7d) upgrades js to `^0.7.0` and it seems if I manually get it back to `^0.6.3`, it still works well. OK, I'll degrade it on the next release.

**Comment by espresso3389** [comment]
Mmm,... [js 0.6.3](https://pub.dev/packages/js/versions/0.6.3) is already 3 years old... Mmm.

Could you please use `dependency_overrides` to fix js to 0.6.3?

**Comment by Yoda-Man** [comment]
Very good idea. I am sure all the projects will upgrade to 0.7.1 soon anyway.

**Comment by espresso3389** [comment]
Now, we have three versions:

- 1.0.X for Flutter 3.19/Dart 3.3
- 0.4.46+ for Flutter 3.16/Dart 3.2.3
- 0.0.46+ for Flutter 3.12/Dart 3.1.0
