### ISSUE TITLE
Provide a way to skip pdfium binary download.

### ISSUE THREAD

**Issue by Tanish2002** [espresso3389/pdfrx#85]
I'm trying to package a flutter app that uses this library for linux.
The problem is that the build environment is a sandbox without internet access.

It would be nice to provide a way to skip the pdfium binary download and make it so that I can provide my own pre-downloaded version of pdfium binary.

I'm sorry if this feature is already present. I don't really understand how CMake works.

**Comment by Tanish2002** [comment]
yes, and I believe they are stored in the build folder, which isn't generated till I build the app.
Manually putting the pdfium binary in the build folder works when I'm building manually on a system.
It doesn't work that way in a sandboxed builder where everything starts from scratch every time. 

I do think maybe an ENV variable check for the `.so` file before downloading might be helpful.
This way we can keep the current way of downloading the latest libs and provide an alternate way for users to just set an ENV var to their own `pdfium.so` file which can be used.

**Comment by espresso3389** [comment]
Did you really check the directory/file structure is identical if your code places predownloaded files?
I think the so file is just missing on the CI machine. No other trick there.

**Comment by Tanish2002** [comment]
I don't get you.
From what I understand.
when `flutter build linux` runs a build folder is created and then the pdfium lib is downloaded and placed in the build folder.
In my case for a release type build it's placed in `build/linux/x64/release/.lib/chromium%2F6259/x64/libpdfium.so`


what I am saying is if we had a way to set the path to `libpdfium.so` using a env var or something else (I don't know how cmake works so I can't think of a better way), then in my package I can simply just pass the Env Variable.

FWIW. I am trying to package for [NixOS](https://nixos.org/).
Here is the manual to it: [here](https://nixos.org/manual/nixpkgs/unstable/#ssec-dart-flutter).
A small example would look like this.
```nix
{  flutter, fetchFromGitHub }:

flutter.buildFlutterApplication {
  pname = "firmware-updater";
  version = "0-unstable-2023-04-30";

  src = fetchFromGitHub {
    owner = "canonical";
    repo = "firmware-updater";
    rev = "6e7dbdb64e344633ea62874b54ff3990bd3b8440";
    sha256 = "sha256-s5mwtr5MSPqLMN+k851+pFIFFPa0N1hqz97ys050tFA=";
  };

  pubspecLock = lib.importJSON ./pubspec.lock.json;
}
```

I don't force you to understand this, but as you can see the way flutter packages are packaged using the inbuilt helper. Adding a env var would make the packaging easier since I would be able to do something like `LIBPDFIUM_SRC=${libpdfium}/lib/libpdfium.so`
where nix can download libpdfium using inbuilt fetcher

**Comment by espresso3389** [comment]
OK, the truth is that it is not easy as you are thinking. It takes longer than you've expected. Please do that by yourself.

**Comment by Tanish2002** [comment]
I'm sorry if I offended you in any way😅.
I never thought it was easy. I did say in my first message that I don't understand how CMake works. My main goal for this issue was to just find a way to bypass the pdfium binary download in some way and provide it myself. 

Anyways thanks for the help and your time. Cheers
