### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by sdegenaar** [espresso3389/pdfrx#86]
If I use the PdfViewer.data and change pdf's data to load difeerent pdf based on links. I get 

The following _TypeError was thrown building PdfViewerScrollThumb(dirty, state: _PdfViewerScrollThumbState#752dc):
Null check operator used on a null value

If I change line 515 in pdf_viewer from 
Rect get _visibleRect => _txController.value.calcVisibleRect(_viewSize!); 

to

Rect get _visibleRect => _txController.value.calcVisibleRect(_viewSize ?? Size(0,0));

the problem goes away and works all good.

Or if I comment out the PdfViewerScrollThumb it works fine too but would like to display the page numbers

Thanks :-)

**Comment by espresso3389** [comment]
OK, there seems some kind of timing issue that PdfViewerScrollThumb accesses visibileRect before PdfViewer fully initialized.
I'll check the code carefully if your suggestion is OK or any other correct fix will be found.

**Comment by wibtu** [comment]
Hi @espresso3389, did you have any time to validate the fix by @sdegenaar? I'm currently facing the same issue when using PdfViewer.data.

**Comment by espresso3389** [comment]
Fixed on 1.0.51 and other branches.
