### ISSUE TITLE
intl 0.19.0 can't resolve versions

### ISSUE THREAD

**Issue by bziembanski** [espresso3389/pdfrx#87]
Hi, there's a known issue, where flutter's internal libraries (such as flutter_localizations) uses older version of package intl 0.18.1. Because of this I can't resolve version in my project. 

It became a problem after upgrading to the newest version of flutter, because I had to update pdfrx to the newer version as well.

Would it be possible for you to lower the version bound or is the newest version of intl critical for this package?

```
Resolving dependencies...
Because pdfrx >=0.4.35 depends on intl ^0.19.0 and every version of core from path depends on intl 0.18.1, pdfrx >=0.4.35 is incompatible with core from path.
```

**Comment by bziembanski** [comment]
Here's the issue on the official flutter repo
https://github.com/flutter/flutter/issues/139861

**Comment by espresso3389** [comment]
Ohh, I should use 0.18.1 even on 1.0.X...

**Comment by espresso3389** [comment]
1.0.11 also fixes the issue anyway.
