### ISSUE TITLE
ScaleUpdateDetails focalPointDelta

### ISSUE THREAD

**Issue by DonRubiczek** [espresso3389/pdfrx#89]
Hey, I am working with PdfViewer version 0.4.47. Over my pdfViewer I have custom positioned widget placed in stack that i want to scale on zoom (its size and position). I am using onInteractionUpdate callback, getting scale from ScaleUpdateDetails, multiplying its size with it works correctly but I also want to scale position and I assumed that focalPointDelta could be useful in that case - documentation says ( The amount the gesture's focal point has moved in the coordinate space of the event receiver since the previous update.) but its value is always 0 and I did not find any part in documentation which explains how to use it.

What should i do to use it?
Or is there any other way to scale position on zoom? 
I would really appreciate any help.

**Comment by espresso3389** [comment]
The most important design dicision on [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html) (and of course, [PdfViewer](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewer-class.html)) is 
that the controller assodicated to the widget is derived from [ValueNotifier&lt;Matrix4&gt;](https://api.flutter.dev/flutter/foundation/ValueNotifier-class.html).

It means that you can be notified when any zoom or scroll position change by subscribing(addListener/removeListener) the controller.

The largest headache with the approach is that it's too difficult to obtain zoom/offset from the matrix. But [PdfViewerController](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerController-class.html) provides you with several helper methods that eases to get [current zoom](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerController/currentZoom.html), [center position](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerController/centerPosition.html), and so on.

**Comment by espresso3389** [comment]
> but its value is always 0 and I did not find any part in documentation which explains how to use it.

I've checked the InteractiveViewer's code (that is just forked version from the Flutter original), only the following lines handles `focalPointDelta`:
https://github.com/espresso3389/pdfrx/blob/c985b456a3a5010ab9f53ef88442e1117ad4930e/lib/src/widgets/interactive_viewer.dart#L952-L966

It seems that the value might be non-zero if the event is from `PointerDeviceKind.trackpad` and _NOT SCALING_. So your assumption is anyway wrong.

**Comment by DonRubiczek** [comment]
Thanks for the reply. Yes, I also tried using matrix properties eg. X,Y, delta X, delta Y, but as you said it was not working as expected. I will try convert my position scaling algorithm to use centerPosition and reply with the result. Also thanks for the explanation with focalPointDelta.

**Comment by DonRubiczek** [comment]
I am working on widgets scaling/ positioning on zooming using PdfViewerController properties (currentZoom, centerPosition). I added listener to controller, but on zooming it is called 2 times with the same currentZoom, but different centerPosition offset. Is it rule that for every zoom value, listener will be called 2 times for the same currentZoom value?

**Comment by espresso3389** [comment]
> but on zooming it is called 2 times with the same currentZoom, but different centerPosition offset. Is it rule that for every zoom value, listener will be called 2 times for the same currentZoom value?
> 
> To be honest it would be nice feature to add to listener parameters indicating whether it was zoomed or scrolled.

Bascally, they're handled on a single matrix value using asynchronous animations. And I cannot tell when or how many times it is changed. And future versions may change the internal logic anyway.

**Comment by DonRubiczek** [comment]
As u advised above I tried using PdfViewerController properties to scale widget above pdfViewer, but using centerPosition does not give results as expected and I do not know if I am doing anything wrong or is it not working correctly. I used onInteractionStart and onInteractionUpdate callbacks because they are called just one time with the same scale value. 
OnInteractionStart I am setting startZoom and startCenterPosition properties that are later used as baseCenterPosition and baseScale to calculate position and size of widget after zooming.

`
onInteractionStart: (details) {
pageController.onStartCenterPosition.value = pageController.pdfViewerController.centerPosition;
pageController.onStartZoomCombined.value = pageController.pdfViewerController.currentZoom;
},
`

On interaction callbacks are called not only on scale but on every user interaction, so at begginning of onInteractionUpdate I am checking if scale value changed regarding one set in onInteractionStart and if yes then I am starting to resize widget size and position.

`
onInteractionUpdate: (details) {

        final startZomm =
            (pageController.onStartZoomCombined.value * 1000).round();
        final updatedZoom =
            (pageController.pdfViewerController.currentZoom * 1000).round();

        if (startZomm == updatedZoom) {
          return;
        }

        pageController.combinedScale.value =
            pageController.pdfViewerController.currentZoom;
        pageController.stampWidth.value =
            pageController.baseStampWidth * pageController.combinedScale.value;
        pageController.stampHeight.value =
            pageController.baseStampHeight * pageController.combinedScale.value;

        final deltaX = pageController.onStartCenterPosition.value.dx -
            pageController.pdfViewerController.centerPosition.dx;
        final deltaY = pageController.onStartCenterPosition.value.dy -
            pageController.pdfViewerController.centerPosition.dy;

        pageController.position.value = Offset(
          pageController.basePosition.dx +
              (deltaX * pageController.combinedScale.value),
          pageController.basePosition.dy +
              (deltaY * pageController.combinedScale.value),
        );
      },
`
After scale check I am setting new scaleValue and resizing widget regarding new scale and baseSize. After that I am trying to scale position counting deltaX, deltaY then multiplying it by scale and adding to start position. 
I made a lot of tests and the delta calculated in this way has a different value than the shift of the PDF view on the screen after scaling. Am I doing anything wrong? 
Scalling widget size on zoom works correctly, just position is wrong.

**Comment by DonRubiczek** [comment]
For example: 

OnInteractionStartPosX = 297.6
OnInteractionStartPosY = 317.3
OnInteractionStartScale = 2.9032258064516125

OnInteractionUpdatePosX = 317.3
OnInteractionUpdatePosY = 314.7 
OnInteractionUpdateScale = 2.972864949361671

then

OnInteractionStartPosX = 302
OnInteractionStartPosY = 314.7  
OnInteractionStartScale = 2.972864949361671

OnInteractionUpdatePosX = 375.3
OnInteractionUpdatePosY = 269.9
OnInteractionUpdateScale = 5

Calculated deltaX = 77.7 * 5 = 388,5
Calculated deltaY = 47.4 * 5 = 237

real pdfViewer deltaX = 543.1
real pdfViewer deltaY  = 140 

For every zooming onInteractionCallbacs are called two times. First one with small zoom change and second one with target zoom.

**Comment by espresso3389** [comment]
Sorry, I didn't understand what you want to achieve. Could you please explain what is your first motivation?

**Comment by DonRubiczek** [comment]
Sure, I want to make pdfViewer that allows user to scroll and zoom it. Above pdfViewer on stack I have rectangle that user can move around the screen to designate a place for signature. I want this rectangle to scale its size and position on zoom to be exactly the same relative to pdfViewer.
<img width="666" alt="Screenshot 2024-03-08 at 11 42 06" src="https://github.com/espresso3389/pdfrx/assets/32109523/ae73716d-5576-4ece-a146-db3868cb97fb">

**Comment by espresso3389** [comment]
I'm thinking...

One possible option is [PdfViewerParams.pageOverlaysBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pageOverlaysBuilder.html), which directly places widgets on the page.

But it may not be suitable for your situation.

**Comment by DonRubiczek** [comment]
I am placing my rectangle in stack above pdfViewer and moving it is working correctly, the only thing that I have problem with is scalling its position on Zoom using controllers' CenterPosition to be exactly the same relatively to pdfViewer. Do you have any idea why?

**Comment by espresso3389** [comment]
OK, so we need to create some simple code to illustrate/check/test the current behavior.

**Comment by DonRubiczek** [comment]
Do you want me to create that and share it?

**Comment by espresso3389** [comment]
Please wait. I'm still thinking. 

[PdfViewerParams.viewerOverlayBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/viewerOverlayBuilder.html) is also implemented using Stack and the approach may be really straight forward. It realizes [scroll thumb](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#showing-scroll-thumbs).
It uses controller's addListener to receive updates on refreshed on each update.

It calculate the view position based on `controller.value.x` / `controller.value.y`:

https://github.com/espresso3389/pdfrx/blob/c5b6d77f40c7f70e15dc462cd857df04001698a9/lib/src/widgets/pdf_viewer_scroll_thumb.dart#L54-L60

**Comment by espresso3389** [comment]
I'm not sure what is the best approach for us. Furthermore, I don't know whether we already have the tool or not.

**Comment by DonRubiczek** [comment]
I will think about your approach with scroll thumb and try to convert my algorithm this way, and get back to you.

**Comment by DonRubiczek** [comment]
Using controller's visibleRect, the intended effect was achieved and scaling of the relative position in relation to the PDF when zooming works correctly. Thank you for the idea. Also I have one more question. I am trying to use PdfViewerParams - minScale and maxScale. Setting maxScale works correctly, but when I am trying to set minScale it does not effect viewer. PdfViewerController has its own value at minimum scale, equal to alternativeFitScale. Is it bug or am I using it wrongly?

**Comment by espresso3389** [comment]
Ah, `minScale` is currently not used...
Basically, I think there's no pragmatic reason to make the page size smaller than `alternativeFitScale`. So it's actually a design and `minScale` _should be removed_.

But do you have any reason to use minScale? If there's some reason to justify the existance of `minScale`, I'll make it work in some future version (though there're many issues around it if used with `boundaryMargin` or such).

**Comment by espresso3389** [comment]
Do you want to disable `alternativeFitScale` ?

**Comment by DonRubiczek** [comment]
I don't know what do you mean by disabling alternativeFitScale. I just want to be able to set minScale to some value and not allow to zoom out smaller than this value.

**Comment by espresso3389** [comment]
For `minScale`, 1.0.50/0.4.50/0.0.50 introduces `PdfViewerParams.useAlternativeFitScaleAsMinScale`, You can set the value to false to enable `minScale`.

**Comment by DonRubiczek** [comment]
@espresso3389 What about that? https://github.com/espresso3389/pdfrx/issues/89#issuecomment-2007370628

**Comment by espresso3389** [comment]
Currently, it's too difficult to place the PDF on the top of the view. It's kind of design tradeoff or such and if I introduce some new feature, it breaks the current consistency. I should think some better handling...

**Comment by espresso3389** [comment]
For the centering issue, I opened a new issue #111.
