### ISSUE TITLE
Allow horizontal pages

### ISSUE THREAD

**Issue by dajack05** [espresso3389/pdfrx#9]
I'm still pretty new to pdfrx, so I might just be missing something, but is there a way to lay pages out horizontally?

If not, that would be a nice feature to have.

**Comment by espresso3389** [comment]
Basically, [PdfViewerParams.layoutPages](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/layoutPages.html) function is to layout pages with custom logic. But it still lacks of page caching control and not fully working so far.

**Comment by TarasBounty** [comment]
@espresso3389 could you provide sample please? I also trying to move from your previous package [pdf_render](https://pub.dev/packages/pdf_render) and there I did via `documentBuilder` and `PdfPageView:`

```
   Widget _previewBuilder(BuildContext context, PdfDocument? pdfDocument, int pageCount) 
        {
        return LayoutBuilder(
         builder: (context, constraints) => ListView.builder(
            scrollDirection: Axis.horizontal,
            itemCount: pageCount,
        itemBuilder: (context, index) => Container(
          child: PdfPageView(
            pdfDocument: pdfDocument,
            pageNumber: index + 1,
          ),
        ),
      ),
    );
  }
```

**Comment by espresso3389** [comment]
@TarasBounty 

The following code is the simplest `layoutPages` function that realizes horizontal layout with [0.3.5](https://pub.dev/packages/pdfrx/versions/0.3.5):

```dart
PdfViewer.uri(
  Uri.parse('https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
  controller: controller,
  displayParams: PdfViewerParams(
    layoutPages: (pages, templatePage, params) {
      final height = pages.where((p) => p != null).fold(
              templatePage.height,
              (prev, page) => max(prev, page!.height)) +
          params.margin * 2;
      final pageLayouts = <Rect>[];
      double x = params.margin;
      for (var page in pages) {
        page ??= templatePage; // in case the page is not loaded yet
        pageLayouts.add(
          Rect.fromLTWH(
            x,
            (height - page.height) / 2, // center vertically
            page.width,
            page.height,
          ),
        );
        x += page.width + params.margin;
      }
      return PageLayout(
        pageLayouts: pageLayouts,
        documentSize: Size(x, height),
      );
    },
  ),
),
```

If you use the older plugin version, there're small breaking change on the API.

**Comment by TarasBounty** [comment]
@espresso3389 How I can change size of pages? I need to do pages with height 60 and width 30
![image](https://github.com/espresso3389/pdfrx/assets/15182848/3f2b5a5b-db64-4cf3-8a3f-f4bacbc610a3)

**Comment by espresso3389** [comment]
@TarasBounty
Basically, the actual page size is calculated from PdfViewer's size. So the solution is just wrap PdfViewer with SizedBox to controll the PdfViewer's height.

By default, the margin is 8 pixel. So height should be 60+8*2.
For the page widths, because they're calculated from the original page aspect ratio, it's not controllable in the case.
And, it seems you don't want user to change the zoom ratio, explicitly disable `scaleEnabled` there:

```dart
SizedBox(
  height: 60+8*2,
  child: PdfViewer.uri(...),
  params: PdfViewerParams(
    scaleEnabled: false,
  ),
),
```

**Comment by TarasBounty** [comment]
@espresso3389 I just want to say that I already used `SizedBox(height:60,...)` with my sample and it renders like that (one page takes full width and I can scroll in any direction to see other pages or scroll down to see curent page):
![image](https://github.com/espresso3389/pdfrx/assets/15182848/163c05eb-ac13-4f57-b7e9-5a5ac52e0d22)

I've tried cope and paste your sample above but it not showing pdf file it's just emptu box with 60 height. Maybe a problem with  `PdfViewer.uri()`? 
Is it works on your side?

**Comment by espresso3389** [comment]
On [README.md on 0.4.2](https://pub.dev/packages/pdfrx/versions/0.4.2#horizontal-scroll-view) illustrates how to do horizontal layout.

But for your purpose,  I just introduced [PdfViewerParams.enableRealSizeRendering](https://pub.dev/documentation/pdfrx/0.4.1/pdfrx/PdfViewerParams/enableRealSizeRendering.html). You had better set it to false to improve the performance.

**Comment by espresso3389** [comment]
0.4.2 also has breaking changes and some "key" features, so the final code will be like:

```dart
SizedBox(
  height: 100,
  child: PdfViewer.uri(
    Uri.parse(
        'https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
    controller: controller,
    // IMPORTANT: fit thumbnails into the SizedBox's view
    anchor: PdfPageAnchor.all,
    displayParams: PdfViewerParams(
      // disable scale changes by user
      scaleEnabled: false,
      // disable high resolution rendering (because we just use thumbnails)
      enableRealSizeRendering: false,
      // code to display pages horizontally
      layoutPages: (pages, params) {
        final height = pages.fold(
                0.0, (prev, page) => max(prev, page.height)) +
            params.margin * 2;
        final pageLayouts = <Rect>[];
        double x = params.margin;
        for (var page in pages) {
          pageLayouts.add(
            Rect.fromLTWH(
              x,
              (height - page.height) / 2, // center vertically
              page.width,
              page.height,
            ),
          );
          x += page.width + params.margin;
        }
        return PdfPageLayout(
          pageLayouts: pageLayouts,
          documentSize: Size(x, height),
        );
      },
    ),
  ),
),
```

**Comment by TarasBounty** [comment]
@espresso3389 Thank you so much!

**Comment by TarasBounty** [comment]
> 0.4.2 also has breaking changes and some "key" features, so the final code will be like:
> 
> ```dart
> SizedBox(
>   height: 100,
>   child: PdfViewer.uri(
>     Uri.parse(
>         'https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
>     controller: controller,
>     // IMPORTANT: fit thumbnails into the SizedBox's view
>     anchor: PdfPageAnchor.all,
>     displayParams: PdfViewerParams(
>       // disable scale changes by user
>       scaleEnabled: false,
>       // disable high resolution rendering (because we just use thumbnails)
>       enableRealSizeRendering: false,
>       // code to display pages horizontally
>       layoutPages: (pages, params) {
>         final height = pages.fold(
>                 0.0, (prev, page) => max(prev, page.height)) +
>             params.margin * 2;
>         final pageLayouts = <Rect>[];
>         double x = params.margin;
>         for (var page in pages) {
>           pageLayouts.add(
>             Rect.fromLTWH(
>               x,
>               (height - page.height) / 2, // center vertically
>               page.width,
>               page.height,
>             ),
>           );
>           x += page.width + params.margin;
>         }
>         return PdfPageLayout(
>           pageLayouts: pageLayouts,
>           documentSize: Size(x, height),
>         );
>       },
>     ),
>   ),
> ),
> ```

Thank you so much!

**Comment by TarasBounty** [comment]
One more point: Is it possible to align items to the left side?
Cause if a document has only one page it is centered:
![image](https://github.com/espresso3389/pdfrx/assets/15182848/a7ace9a9-9cfb-46bf-b4ad-0eea08e0c717)

**Comment by TarasBounty** [comment]
> @espresso3389 One more point: Is it possible to align items to the left side? Cause if a document has only one-two pages it is centered: ![image](https://private-user-images.githubusercontent.com/15182848/294866786-a7ace9a9-9cfb-46bf-b4ad-0eea08e0c717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ1OTQsIm5iZiI6MTcwNTM4NDI5NCwicGF0aCI6Ii8xNTE4Mjg0OC8yOTQ4NjY3ODYtYTdhY2U5YTktOWNmYi00NmJmLWI0YWQtMGVlYTA4ZTBjNzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZjBmODBlNmZhOGRjMTU2ZmY0NmI1YWMyM2EzM2ZlZDg5ZWU3ZDNmZDk2ZTZiNTIwZWM2YWE5ZjRhNzZhZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyNlHIgoTiN7EJ9FVL2cvTo3qsof-ZEh41NHeJwO1Po)

@espresso3389

**Comment by espresso3389** [comment]
Ah, sorry, I'm forget the centering issue and reopen the issue anyway.
I'm thinking how to do that...

**Comment by espresso3389** [comment]
@TarasBounty for the centering issue, I created another issue #32.
