### ISSUE TITLE
How to fetch pdf first page as image formate

### ISSUE THREAD

**Issue by Prafu-94** [espresso3389/pdfrx#90]
If we want get particular any single page as image formate then we can also depends on other library so can be possible to fetch pdf first page as image.

**Comment by espresso3389** [comment]
Do you want to have PdfPage.save or something like that?

**Comment by Prafu-94** [comment]
no, i have pdf file fetch from local or any where else but after that i want to display pdf first page as  thumbnail. only fetch first page as image formate for create thumbnail

**Comment by Prafu-94** [comment]
i mean, i want only fetch pdf first page as jpeg or png or any other image formate. thats all

**Comment by espresso3389** [comment]
So, you don't need PdfViewer? Just open your file and create image file for the first page?

**Comment by Prafu-94** [comment]
yes

**Comment by espresso3389** [comment]
Basically, pdfrx is a PDF viewer so you should explain your purpose first.

So, if so, as I've suggested once on this issue, PdfPage.saveAsImageFile or PdfImage.saveAsImageFile is enough. What is your intention?

**Comment by espresso3389** [comment]
Your image is broken :(
![image](https://github.com/espresso3389/pdfrx/assets/1311400/f788895d-325c-46f1-8d20-e23c243ae11d)

**Comment by espresso3389** [comment]
To show certain PDF page, you can use [PdfDocumentViewBuilder/PdfPageView](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#pdfdocumentviewbuilderpdfpageview).

**Comment by espresso3389** [comment]
So the conclusion seems that you don't need JPEG image save function. Correct?

**Comment by Prafu-94** [comment]
my goal is simple i want only fetch pdf page as image formate. Because if larger amount of data then if i have load file using builder then it consumes more memory.

**Comment by espresso3389** [comment]
No your goal is not fetching something. Please use [PdfDocumentViewBuilder/PdfPageView](https://github.com/espresso3389/pdfrx?tab=readme-ov-file#pdfdocumentviewbuilderpdfpageview). It's easy enough.

**Comment by espresso3389** [comment]
> Because if larger amount of data then if i have load file using builder then it consumes more memory.

PdfDocumentViewBuilder/PdfPageView loads data that is required to render the specified page. But if you use [PdfDocument](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder/PdfDocumentViewBuilder.uri.html), by default it downloads all the PDF file bytes.

In some special case (linearized PDF or some sparce PDF served on HTTP range-access), you can reduce the byte size downloaded by using the following strategy:

1, [PdfDocumentRefUri](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentRefUri-class.html) to enable `preferRangeAccess`
2, Use [PdfDocumentViewBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfDocumentViewBuilder/PdfDocumentViewBuilder.html) explicitly to accept the document reference returned by the function

**Comment by espresso3389** [comment]
As a side node, because PDF file is not just a bundle of single page images, extracting just one page might require whole PDF file.
