### ISSUE TITLE
Allow Scaling all pages to fit viewer width

### ISSUE THREAD

**Issue by drexhacker** [espresso3389/pdfrx#91]
@espresso3389 Thanks for this amazing package that has really simplified my work as I just shifted from using `printing` package which is also based on `pdfium` . I landed on this package and it works very well and actually performs way better than the previous one I was using. But there is just one thing I liked about the previous one and I haven't been to archive the same with this package and it is that in the previous all my pages are rendered in the same size for instance `A4` despite the difference in page sizes and for this one I have so far failed to archive the same.
Here is an image of how my pages are being rendered with this Package;
![image](https://github.com/espresso3389/pdfrx/assets/63024937/c4311cc7-84ef-4fcf-962b-17c085269a76)
As seen above I would like the pages to scale to fit atleast to viewer width. 

So far I have tried rendering with horizontal scroll and it is more readable but still this is not my intended scrolling axis.

Any help is appreciated Thank You!

**Comment by espresso3389** [comment]
[PdfViewerParams.layoutPages](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/layoutPages.html) is a function to customize the page layout logic and the following fragment does what you want:

```dart
PdfViewer.asset(
  'assets/test.pdf',
  params: PdfViewerParams(
    enableTextSelection: true,
    maxScale: 8,
    layoutPages: (pages, params) {
      final width = pages.fold(
          0.0, (prev, page) => max(prev, page.width));
      final pageLayouts = <Rect>[];
      double y = params.margin;
      for (final page in pages) {
        final height = page.height * (width / page.width);
        pageLayouts.add(
          Rect.fromLTWH(
            params.margin,
            y,
            width,
            height,
          ),
        );
        y += height + params.margin;
      }
      return PdfPageLayout(
        pageLayouts: pageLayouts,
        documentSize: Size(width + params.margin * 2, y),
      );
    },
```

Please note that the changes to `layoutPages` function does not do hot-reload.

**Comment by drexhacker** [comment]
@espresso3389 First of all sorry for reopening this but I just realized that when I apply the above solution I actually get a blurry result of the render. Kindly help because this is very close to what I want but then readability is very keen.
Screenshot When I apply the layout that you provided
![Screenshot_20240305_201457](https://github.com/espresso3389/pdfrx/assets/63024937/4ab0df71-ba88-4b6d-a8d5-cabf79c198cc)

Screenshot When I just zoom in the page
![Screenshot_20240305_202011](https://github.com/espresso3389/pdfrx/assets/63024937/133b6ae5-5745-4e27-bccf-a470ef02a33b)

Any further help is really appreciated thank you.

**Comment by espresso3389** [comment]
Basically, to reduce the total memory consumption, the page rendering ratio is limited to 4.16x (300 / 72).

The behavior "seems" to be caused by the limit because the pages rendered blurry are very small.

The workaround for the issue is to use [PdfViewerParams.getPageRenderingScale](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/getPageRenderingScale.html).

To check whether my assumption is true or not, please insert the following code to your app:

```dart
PdfViewerParams(
   ...
   getPageRenderingScale: (context, page, controller, estimatedScale) {
    return 3000 / 72; // zoom maximum to 41.6x
  },
),
```

If the code above fixes your issue, we should consider better way to deal with the issue (because the code above removes the memory consumption limit anyway).

**Comment by drexhacker** [comment]
@espresso3389 When I insert the above lines then Document doesn't render and I get the following errors.
```
[ERROR:flutter/lib/ui/painting/image_decoder_skia.cc(87)] Could not create image from decompressed bytes.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Codec failed to produce an image, possibly due to invalid image data.
```
I also noticed that the program is actually eating up he memory yet I have 16GB of RAM

**Comment by espresso3389** [comment]
Oh, `3000 / 72` is too large. So, yes, we should determine the zoom ratio according to `page.width` and `page.height`...

How about the following code?

```dart
PdfViewerParams(
   ...
   getPageRenderingScale: (context, page, controller, estimatedScale) {
    return 3000 / page.width;
  },
),
```

**Comment by drexhacker** [comment]
@espresso3389 This solves the issue as you can see.
![image](https://github.com/espresso3389/pdfrx/assets/63024937/0e47011e-dc00-408e-b04e-2759c1bc5e40)

**Comment by espresso3389** [comment]
To see the things better, could you please give me the log output by adding `print` to your code anyway?

```dart
PdfViewerParams(
   ...
   getPageRenderingScale: (context, page, controller, estimatedScale) {
    print('Page ${page.pageNumber}: ${page.width}x${page.height}');
    return 3000 / page.width;
  },
),
```

**Comment by espresso3389** [comment]
The code above assumes 3000 pixels width is a good choise for PDF rendering.

But if it's just a Desktop application, 2000 pixels or even smaller size may be better choise for memory consumption and rendering speed and, of course for the visual quality.

**Comment by drexhacker** [comment]
> ```dart
> print('Page ${page.pageNumber}: ${page.width}x${page.height}');
> ```

Here is the requested log output
```
flutter: Page 1: 3720.75x2631.0
flutter: Page 2: 595.2760009765625x841.8900146484375
flutter: Page 3: 595.2760009765625x841.8900146484375
```

**Comment by drexhacker** [comment]
> The code above assumes 3000 pixels width is a good choise for PDF rendering.
> 
> But if it's just a Desktop application, 2000 pixels or even smaller size may be better choise for memory consumption and rendering speed and, of course for the visual quality.

The target audience is Schools but we also looking at individual students hence we would love to support both desktop and mobile. So I really appreciate your advise Sir.

**Comment by drexhacker** [comment]
@espresso3389 I think I should close this now. And also Thanks so much for the help?

**Comment by drexhacker** [comment]
@espresso3389 Hello Thank You for the package but on updating to the latest version the provided solution below no longer works.

> To see the things better, could you please give me the log output by adding `print` to your code anyway?
> 
> ```dart
> PdfViewerParams(
>    ...
>    getPageRenderingScale: (context, page, controller, estimatedScale) {
>     print('Page ${page.pageNumber}: ${page.width}x${page.height}');
>     return 3000 / page.width;
>   },
> ),
> ```

The Page fits the viewer but content is blurry again. Thank You!

**Comment by thomas4Bitcraft** [comment]
@drexhacker  I have the same problem again - it was solved in a previous release. @drexhacker Did you found a solution for it?

**Comment by drexhacker** [comment]
@thomas4Bitcraft Hmmm not really but I had to stick to version `<=1.0.49` and use the following

> To see the things better, could you please give me the log output by adding `print` to your code anyway?
> 
> ```dart
> PdfViewerParams(
>    ...
>    getPageRenderingScale: (context, page, controller, estimatedScale) {
>     print('Page ${page.pageNumber}: ${page.width}x${page.height}');
>     return 3000 / page.width;
>   },
> ),
> ```
This is the snippet am still using up to now, it works but I remember @espresso3389 mentioning it's performance implications though it's workable
