### ISSUE TITLE
pdfrx currently does not support ios12？

### ISSUE THREAD

**Issue by zengchanghuan** [espresso3389/pdfrx#92]
pdfrx currently does not support ios12. Is there any way to support ios12?

**Comment by espresso3389** [comment]
I've created [ios12-support branch](https://github.com/espresso3389/pdfrx/tree/ios12-support) and it seems it works well on my own device.

But I'm not able to test it against the actual iOS device /iOS 12 Simulator.

So could you please test the branch with your devices? If it works well, I'll merge the changes to release channels.

**Comment by zengchanghuan** [comment]
<img width="389" alt="截屏2024-03-05 15 23 18" src="https://github.com/espresso3389/pdfrx/assets/2323551/d8ba9f03-f44d-42ec-88d2-c955289e96e5">
<img width="1105" alt="截屏2024-03-05 15 23 31" src="https://github.com/espresso3389/pdfrx/assets/2323551/ab7ccedd-d4a0-4bb1-8de5-79ea6c42a208">
Minimum Deloyment is still ios 13.0.

**Comment by espresso3389** [comment]
Did you do `flutter clean/flutter pub get` after switching `pdfrx` source on pubspec.yaml?

**Comment by zengchanghuan** [comment]
Yes.I run flutter clean and flutter pub get.But I don not know how to switching pdfrx source on pubspec.yaml?

**Comment by espresso3389** [comment]
Wow, you're working on published version? It is still on a branch and not published.

Change pubspec.yaml's pdfrx like the following one:

```yaml
  pdfrx:
    git:
      url: https://github.com/espresso3389/pdfrx
      ref: ios12-support
```

Once you've finished the testing work and confirmed that everything works well, I'll do some more work to make it available to pub.dev.

**Comment by zengchanghuan** [comment]
Yes,Now it is can run on the ios12.I tested it on the ios12 devices.Thank you so much.
