### ISSUE TITLE
save edited pdf in local storage

### ISSUE THREAD

**Issue by Prafu-94** [espresso3389/pdfrx#98]
I have add annotation section in which selected text can high light but how pdf  save in local storage after edit file. and i have use   pdfrx: ^0.4.44 version

**Comment by espresso3389** [comment]
pdfrx is just a viewer. No editing feature. What do you want to save?

**Comment by Prafu-94** [comment]
your example in you show four circle for highlight , so here am able to  highlight text but i want save this high light permeant in pdf

**Comment by espresso3389** [comment]
Ah, currently no such feature. The marker feature is just a demonstration of how to memorize a rectangle and navigate to it.

**Comment by Prafu-94** [comment]
so any other approach which help me to save it?

**Comment by espresso3389** [comment]
pdfrx currently only has APIs to decode PDF file. Many PDF editing feature provided by pdfium is not exported.
To implementing editing "relatively" easy and fast, you'd better use another PDF plugin.

And, frankly speaking, I don't/won't plan to provide such editing feature on pdfrx. It's just a viewer.
