### ISSUE TITLE
Issue while changing state

### ISSUE THREAD

**Issue by dhruvhighspot** [espresso3389/pdfrx#99]
It shows Exception in hasSize
<img width="1100" alt="Screenshot 2024-03-11 at 3 06 57 PM" src="https://github.com/espresso3389/pdfrx/assets/156050023/ced285db-40da-42b8-bb91-903c80ff1027">

**Comment by espresso3389** [comment]
The screenshot does not have any useful information.
Please show me the actual stacktrace or something in "text" not in screenshot.
